#line 2 "lex.yy.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT

#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern int yylineno;
int yylineno = 1;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 80
#define YY_END_OF_BUFFER 81
static yyconst short int yy_acclist[255] =
    {   0,
       81,   80,   30,   79,   80,   53,   80,   80,    1,   80,
       66,   80,   78,   80,   80,   72,   80,   73,   80,   64,
       80,   62,   80,   69,   80,   63,   80,   68,   80,   65,
       80,   28,   80,   28,   80,   70,   80,   71,   80,   40,
       80,   42,   80,   41,   80,   26,   80,   27,   80,   27,
       80,   27,   80,   27,   80,   74,   80,   75,   80,   55,
       80,   27,   80,   27,   80,   27,   80,   27,   80,   27,
       80,   27,   80,   27,   80,   27,   80,   27,   80,   27,
       80,   27,   80,   27,   80,   25,   27,   31,   80,   76,
       80,   54,   80,   77,   80,   67,   80,   37,   35,   29,

       29,    1,   47,   52,   29,   61,   45,   59,   43,   60,
       44,   46,   28,   28,   58,   38,   36,   34,   32,   39,
       57,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,    5,   27,   27,   15,   27,   27,
       27,   27,   27,   27,   27,   51,   29,   29,   29,   28,
       50,   33,   48,   56,   27,   27,   27,   27,   27,   27,
       27,   27,   13,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   49,   27,   23,   27,   24,
       27,   27,   27,    6,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   20,   27,   27,   27,   21,   27,   27,

       27,   22,   27,   11,   27,   27,   27,   19,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   18,   27,   16,
       27,   27,    8,   27,   27,   27,   27,    9,   27,   27,
       27,   17,   27,   10,   27,   27,   14,   27,   27,   27,
        7,   27,   27,   12,   27,    2,   27,   27,   27,   27,
        3,   27,    4,   27
    } ;

static yyconst short int yy_accept[202] =
    {   0,
        1,    1,    1,    2,    3,    6,    8,    9,   11,   13,
       15,   16,   18,   20,   22,   24,   26,   28,   30,   32,
       34,   36,   38,   40,   42,   44,   46,   48,   50,   52,
       54,   56,   58,   60,   62,   64,   66,   68,   70,   72,
       74,   76,   78,   80,   82,   84,   86,   90,   92,   94,
       96,   98,   99,  100,  100,  101,  102,  102,  103,  104,
      105,  105,  106,  106,  107,  108,  109,  110,  111,  112,
      113,  114,  115,  115,  116,  117,  118,  119,  119,  120,
      121,  122,  123,  124,  125,  126,  127,  128,  129,  130,
      131,  132,  133,  134,  135,  137,  138,  140,  141,  142,

      143,  144,  145,  146,  147,  147,  147,  147,  148,  149,
      149,  149,  150,  150,  151,  152,  153,  154,  155,  156,
      157,  158,  159,  160,  161,  162,  163,  165,  166,  167,
      168,  169,  170,  171,  172,  173,  174,  175,  176,  176,
      176,  177,  178,  180,  182,  183,  184,  186,  187,  188,
      189,  190,  191,  192,  193,  194,  196,  197,  198,  200,
      201,  202,  204,  206,  207,  208,  210,  211,  212,  213,
      214,  215,  216,  217,  218,  220,  222,  223,  225,  226,
      227,  228,  230,  231,  232,  234,  236,  237,  239,  240,
      241,  243,  244,  246,  248,  249,  250,  251,  253,  255,

      255
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,    1,   27,   28,   29,   29,   29,   30,   31,
       32,   32,   32,   32,   32,   33,   32,   34,   32,   32,
       32,   35,   36,   37,   38,   32,   32,   39,   32,   32,
       40,   41,   42,   43,   44,    1,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   32,   54,   55,   56,   57,
       58,   59,   32,   60,   61,   62,   63,   64,   65,   66,
       32,   32,   67,   68,   69,   70,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[71] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    1,    1,    1,    1,    1,    1,    4,    4,    4,
        4,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    1,    1,    5,    4,    4,    4,    4,    4,    4,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[211] =
    {   0,
        0,    0,  137,  746,  746,   46,   66,    0,  106,  112,
       67,  746,  746,   61,   64,  746,   59,  746,   95,   60,
       71,  746,  746,   58,   60,   88,  746,   75,   81,   84,
       98,  746,  746,  746,  104,  108,  115,  120,  124,  130,
      127,  133,  139,  142,  136,  148,  152,  746,   47,  746,
      746,  746,  746,  184,  746,   91,  185,    0,  746,  746,
      191,  746,  199,  746,  746,  746,  746,  746,  746,  746,
      155,  187,    0,   86,  746,  746,  746,   86,  746,  746,
       62,    0,  191,  194,  197,  200,  203,  214,  222,  225,
      230,  234,  238,  241,  244,  247,  253,  256,  259,  267,

      270,  277,  288,  746,  136,  306,  295,  305,  307,  312,
      313,  314,  321,    0,  746,  746,  746,   81,  323,  330,
      337,  345,  349,  352,  355,  358,  361,  365,  368,  372,
      376,  379,  383,  386,  396,  401,  407,  413,  198,  433,
      746,  421,  424,  427,  433,  436,  442,  445,  450,  456,
      459,  462,  465,  471,  474,  477,  483,  489,  492,  495,
      498,  503,  511,  516,  519,  522,  525,  532,  535,  538,
      541,  544,  547,  550,  555,  558,  563,  572,  575,  578,
      584,  591,  594,  597,  600,  603,  610,  613,  618,  621,
      625,  628,  631,  634,  637,  643,  646,  649,  657,  746,

      706,  711,  716,  718,  723,  728,  733,   94,  735,  740
    } ;

static yyconst short int yy_def[211] =
    {   0,
      200,    1,  200,  200,  200,  200,  201,  202,  200,  200,
      203,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  204,  204,  204,
      204,  200,  200,  200,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  200,  200,  200,
      200,  200,  200,  201,  200,  205,  206,  202,  200,  200,
      203,  200,  207,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  208,  200,  200,  200,  200,  200,  200,  200,
      200,  209,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,

      204,  204,  204,  200,  205,  210,  201,  201,  201,  206,
      203,  203,  207,  208,  200,  200,  200,  200,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  205,  210,
      200,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,    0,

      200,  200,  200,  200,  200,  200,  200,  200,  200,  200
    } ;

static yyconst short int yy_nxt[817] =
    {   0,
        4,    5,    5,    4,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       21,   22,   23,   24,   25,   26,   27,   28,   28,   28,
       29,   28,   28,   30,   28,   28,   31,   28,   28,   32,
        4,   33,   34,   28,   28,   35,   36,   28,   37,   38,
       39,   28,   40,   28,   41,   28,   42,   28,   28,   43,
       28,   44,   45,   28,   46,   47,   48,   49,   50,   51,
       52,   55,   62,   64,   68,   56,   62,   66,   71,   71,
       72,   74,   75,   69,   76,   65,  117,  118,   67,   72,
       72,   72,   78,   82,   82,   82,   62,  114,   73,   82,

       82,   82,   82,   82,   82,  141,   57,   63,   84,  116,
      115,   79,   80,   81,  104,   53,   82,   82,   82,   70,
       60,   85,   82,   82,   82,   73,   82,   82,   82,   77,
       59,  106,   86,   82,   82,   82,  200,  200,   82,   82,
       82,   62,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   87,   91,   88,   82,   82,   82,   89,
       82,   82,   82,   71,   71,   72,  106,   92,   94,   95,
       90,  200,   93,  200,   98,   96,   97,  100,   54,   55,
      108,  200,  102,   56,  109,   99,   62,  200,  200,  103,

       62,  101,   61,   62,  112,   72,   72,   72,  112,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   57,  110,  119,  200,  200,  120,
      200,   63,   82,   82,   82,  200,  200,  121,  106,  113,
       82,   82,   82,   82,   82,   82,  200,  200,   82,   82,
       82,  122,   82,   82,   82,  200,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,  200,  200,
      123,   82,   82,   82,   82,   82,   82,   82,   82,   82,
      200,  200,  124,  125,  126,   82,   82,   82,   82,   82,
       82,  200,  200,  127,  128,   82,   82,   82,  129,  131,

       55,  200,  132,  200,   56,  130,   82,   82,   82,  105,
       55,   56,   55,  133,   56,   54,   56,  108,   62,   62,
      200,  109,   62,   62,   61,  134,  112,  200,  135,  200,
      112,  200,  136,  200,  200,   57,  200,  200,  137,  200,
      138,   82,   82,   82,  200,   57,  140,   57,   82,   82,
       82,  200,  110,   63,   63,   82,   82,   82,  142,  200,
      200,  113,  143,   82,   82,   82,  144,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,  200,   82,   82,   82,   82,   82,   82,  145,
       82,   82,   82,  200,   82,   82,   82,   82,   82,   82,

      147,   82,   82,   82,   82,   82,   82,  200,  200,  150,
      146,  151,  148,  152,   82,   82,   82,  200,  149,   82,
       82,   82,  200,  155,  200,   82,   82,   82,  200,  153,
      154,   82,   82,   82,  157,  200,  105,  156,   56,   82,
       82,   82,   82,   82,   82,   82,   82,   82,  200,  159,
      162,   82,   82,   82,   82,   82,   82,  200,  158,  160,
       82,   82,   82,   82,   82,   82,  200,  161,   82,   82,
       82,  200,  200,  140,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,  163,  200,  164,   82,
       82,   82,   82,   82,   82,   82,   82,   82,  166,  200,

      167,   82,   82,   82,  165,  200,  169,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,  200,
      168,   82,   82,   82,  170,  200,  200,  173,  172,   82,
       82,   82,  200,  171,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,  176,  200,  174,  175,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,  179,  177,   82,   82,   82,   82,   82,   82,  200,
      178,   82,   82,   82,  180,  200,  200,  184,  183,  181,
       82,   82,   82,   82,   82,   82,   82,   82,   82,  182,

      200,  200,   82,   82,   82,  200,  186,  200,  185,   82,
       82,   82,   82,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,  200,  187,  188,  190,   82,   82,
       82,   82,   82,   82,  200,  189,   82,   82,   82,   82,
       82,   82,  191,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,   82,   82,   82,   82,  193,  200,
      192,   82,   82,   82,   82,   82,   82,   82,   82,   82,
      200,  200,  196,  200,  194,   82,   82,   82,  200,  200,
      200,  197,  200,  200,  195,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,

      200,  200,  198,  200,  200,  199,   54,  200,  200,   54,
       54,   58,  200,   58,   58,   58,   61,  200,  200,   61,
       61,   83,   83,  105,  200,  200,  105,  105,  107,  200,
      107,  107,  107,  111,  200,  111,  111,  111,   82,   82,
      139,  200,  139,  139,  139,    3,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,

      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200
    } ;

static yyconst short int yy_chk[817] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        6,    7,   11,   14,   17,    7,   11,   15,   20,   20,
       20,   24,   24,   17,   25,   14,   81,   81,   15,   21,
       21,   21,   26,   28,   28,   28,   56,  208,   20,   29,

       29,   29,   30,   30,   30,  118,    7,   11,   29,   78,
       74,   26,   26,   26,   49,    6,   31,   31,   31,   19,
       10,   30,   35,   35,   35,   20,   36,   36,   36,   25,
        9,   56,   31,   37,   37,   37,    3,    0,   38,   38,
       38,  105,   39,   39,   39,   41,   41,   41,   40,   40,
       40,   42,   42,   42,   45,   45,   45,   43,   43,   43,
       44,   44,   44,   35,   38,   36,   46,   46,   46,   37,
       47,   47,   47,   71,   71,   71,  105,   38,   39,   40,
       37,    0,   38,    0,   41,   40,   40,   43,   57,   54,
       57,    0,   45,   54,   57,   42,   61,    0,    0,   46,

       61,   44,   63,  139,   63,   72,   72,   72,   63,   83,
       83,   83,   84,   84,   84,   85,   85,   85,   86,   86,
       86,   87,   87,   87,   54,   57,   84,    0,    0,   85,
        0,   61,   88,   88,   88,    0,    0,   86,  139,   63,
       89,   89,   89,   90,   90,   90,    0,    0,   91,   91,
       91,   87,   92,   92,   92,    0,   93,   93,   93,   94,
       94,   94,   95,   95,   95,   96,   96,   96,    0,    0,
       88,   97,   97,   97,   98,   98,   98,   99,   99,   99,
        0,    0,   89,   90,   91,  100,  100,  100,  101,  101,
      101,    0,    0,   92,   93,  102,  102,  102,   94,   97,

      107,    0,   98,    0,  107,   96,  103,  103,  103,  106,
      108,  106,  109,   99,  108,  110,  109,  110,  111,  112,
        0,  110,  111,  112,  113,  100,  113,    0,  100,    0,
      113,    0,  101,    0,    0,  107,    0,    0,  102,    0,
      103,  119,  119,  119,    0,  108,  106,  109,  120,  120,
      120,    0,  110,  111,  112,  121,  121,  121,  119,    0,
        0,  113,  120,  122,  122,  122,  121,  123,  123,  123,
      124,  124,  124,  125,  125,  125,  126,  126,  126,  127,
      127,  127,    0,  128,  128,  128,  129,  129,  129,  122,
      130,  130,  130,    0,  131,  131,  131,  132,  132,  132,

      124,  133,  133,  133,  134,  134,  134,    0,    0,  127,
      123,  128,  125,  129,  135,  135,  135,    0,  126,  136,
      136,  136,    0,  132,    0,  137,  137,  137,    0,  130,
      131,  138,  138,  138,  134,    0,  140,  133,  140,  142,
      142,  142,  143,  143,  143,  144,  144,  144,    0,  136,
      142,  145,  145,  145,  146,  146,  146,    0,  135,  137,
      147,  147,  147,  148,  148,  148,    0,  138,  149,  149,
      149,    0,    0,  140,  150,  150,  150,  151,  151,  151,
      152,  152,  152,  153,  153,  153,  145,    0,  146,  154,
      154,  154,  155,  155,  155,  156,  156,  156,  149,    0,

      150,  157,  157,  157,  148,    0,  152,  158,  158,  158,
      159,  159,  159,  160,  160,  160,  161,  161,  161,    0,
      151,  162,  162,  162,  153,    0,    0,  157,  155,  163,
      163,  163,    0,  154,  164,  164,  164,  165,  165,  165,
      166,  166,  166,  167,  167,  167,  161,    0,  158,  160,
      168,  168,  168,  169,  169,  169,  170,  170,  170,  171,
      171,  171,  172,  172,  172,  173,  173,  173,  174,  174,
      174,  167,  164,  175,  175,  175,  176,  176,  176,    0,
      165,  177,  177,  177,  168,    0,    0,  172,  171,  169,
      178,  178,  178,  179,  179,  179,  180,  180,  180,  170,

        0,    0,  181,  181,  181,    0,  174,    0,  173,  182,
      182,  182,  183,  183,  183,  184,  184,  184,  185,  185,
      185,  186,  186,  186,    0,  177,  179,  181,  187,  187,
      187,  188,  188,  188,    0,  180,  189,  189,  189,  190,
      190,  190,  183,  191,  191,  191,  192,  192,  192,  193,
      193,  193,  194,  194,  194,  195,  195,  195,  187,    0,
      184,  196,  196,  196,  197,  197,  197,  198,  198,  198,
        0,    0,  192,    0,  189,  199,  199,  199,    0,    0,
        0,  195,    0,    0,  190,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,  196,    0,    0,  197,  201,    0,    0,  201,
      201,  202,    0,  202,  202,  202,  203,    0,    0,  203,
      203,  204,  204,  205,    0,    0,  205,  205,  206,    0,
      206,  206,  206,  207,    0,  207,  207,  207,  209,  209,
      210,    0,  210,  210,  210,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,

      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "lex.l"
#define INITIAL 0
#line 2 "lex.l"
#include <stdio.h>
#include "y_tab.h"
void count();

#line 659 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 13 "lex.l"


#line 809 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 201 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 746 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
					{
					yy_full_match = yy_cp;
					break;
					}
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					++yylineno;
			}

do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 15 "lex.l"
{ count(); return(COMMENT); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 17 "lex.l"
{ count(); return(FUNCTION); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 19 "lex.l"
{ count(); return(LOCAL); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 20 "lex.l"
{ count(); return(GLOBAL); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 23 "lex.l"
{ count(); return(IF); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 24 "lex.l"
{ count(); return (ELSE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 25 "lex.l"
{ count(); return(INCLUDE); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 26 "lex.l"
{ count(); return(EXPORT); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 27 "lex.l"
{ count(); return(IMPORT); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 29 "lex.l"
{ count(); return(RETURN); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 30 "lex.l"
{ count(); return(BREAK); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 31 "lex.l"
{ count(); return(CONTINUE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 33 "lex.l"
{ count(); return(FOR); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 34 "lex.l"
{ count(); return(FOREACH); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 35 "lex.l"
{ count(); return(IN_ITER); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 36 "lex.l"
{ count(); return(WHILE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 37 "lex.l"
{ count(); return(REPEAT); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 39 "lex.l"
{ count(); return(UNTIL); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 40 "lex.l"
{count(); return(FALSE); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 41 "lex.l"
{ count(); return(_NULL_); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 42 "lex.l"
{ count(); return(TRUE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 43 "lex.l"
{count(); return(FALSE); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 44 "lex.l"
{ count(); return(_NULL_); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 45 "lex.l"
{ count(); return(TRUE); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 46 "lex.l"
{ count(); return(REP); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 47 "lex.l"
{ count(); return('@'); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 49 "lex.l"
{ count(); return(IDENT); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 50 "lex.l"
{ count(); return(INT); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 51 "lex.l"
{ count(); return(STRING); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 52 "lex.l"
{ count(); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 53 "lex.l"
{ count(); return(REP); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 54 "lex.l"
{ count(); return(SUBSTR_EQ); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 55 "lex.l"
{ count(); return(SUBSTR_NEQ); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 57 "lex.l"
{ count(); return(REGEX_EQ); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 58 "lex.l"
{ count(); return(REGEX_NEQ); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 60 "lex.l"
{ count(); return(CMP_EQ); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 61 "lex.l"
{ count(); return(CMP_NEQ); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 62 "lex.l"
{ count(); return(CMP_LE); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 63 "lex.l"
{ count(); return(CMP_GE); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 64 "lex.l"
{ count(); return('<'); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 65 "lex.l"
{ count(); return('>'); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 67 "lex.l"
{count(); return('='); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 68 "lex.l"
{ count(); return(ADD_ASS); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 69 "lex.l"
{ count(); return(SUB_ASS); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 70 "lex.l"
{ count(); return(MUL_ASS); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 71 "lex.l"
{ count(); return(DIV_ASS); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 72 "lex.l"
{ count(); return(MOD_ASS); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 73 "lex.l"
{ count(); return(SR_ASS); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 74 "lex.l"
{ count(); return(SRR_ASS); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 75 "lex.l"
{ count(); return(SL_ASS); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 77 "lex.l"
{ count(); return(OR); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 78 "lex.l"
{ count(); return(AND); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 79 "lex.l"
{ count(); return('!'); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 81 "lex.l"
{ count(); return('|'); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 82 "lex.l"
{ count(); return('^'); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 83 "lex.l"
{ count(); return(SRR); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 84 "lex.l"
{ count(); return(SR); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 85 "lex.l"
{ count(); return(SL); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 87 "lex.l"
{ count(); return(INC); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 88 "lex.l"
{ count(); return(DEC); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 90 "lex.l"
{ count(); return(POWER); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 92 "lex.l"
{ count(); return('+'); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 93 "lex.l"
{ count(); return('-'); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 94 "lex.l"
{ count(); return('*'); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 95 "lex.l"
{ count(); return('/'); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 96 "lex.l"
{ count(); return('%'); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 98 "lex.l"
{ count(); return('~'); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 100 "lex.l"
{ count(); return('.'); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 101 "lex.l"
{ count(); return(','); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 102 "lex.l"
{ count(); return(':'); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 103 "lex.l"
{ count(); return(';'); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 104 "lex.l"
{ count(); return('('); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 105 "lex.l"
{ count(); return(')'); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 106 "lex.l"
{ count(); return('['); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 107 "lex.l"
{ count(); return(']'); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 108 "lex.l"
{ count(); return('{'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 109 "lex.l"
{ count(); return('}'); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 111 "lex.l"
{ count(); return('&'); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 114 "lex.l"
{ count(); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 118 "lex.l"
ECHO;
	YY_BREAK
#line 1300 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 201 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 201 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	*yy_state_ptr++ = yy_current_state;
	yy_is_jam = (yy_current_state == 200);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	if ( c == '\n' )
		--yylineno;

	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	if ( c == '\n' )
		++yylineno;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 118 "lex.l"



int flag = 0;
int column = 0;
void count()
{
	int i;
	int j;
	if(flag == 0)
	{
		printf("%d||    ", yylineno);
		flag = 1;
	}		
	ECHO;
	for (i = 0; yytext[i] != '\0'; i++)
		if (yytext[i] == '\n'){
			column = 0;
			printf("%d||	", yylineno);
			
		}
			
		else if (yytext[i] == '\t')
			column += 8 - (column % 8);
		else
			column++;
}