#
# (C) Tenable Network Security, Inc.
#
# The descriptive text and package checks in this plugin were  
# extracted from Red Hat Security Advisory RHSA-2007:1076 and 
# CentOS Errata and Security Advisory 2007:1076 respectively.
#

include("compat.inc");

if (description)
{
  script_id(29255);
  script_version("$Revision: 1.12 $");
  script_cvs_date("$Date: 2015/05/19 23:34:18 $");

  script_cve_id("CVE-2006-7228", "CVE-2007-2052", "CVE-2007-4965");
  script_bugtraq_id(25696, 26462);
  script_osvdb_id(35247, 40142);
  script_xref(name:"RHSA", value:"2007:1076");

  script_name(english:"CentOS 3 / 4 : python (CESA-2007:1076)");
  script_summary(english:"Checks rpm output for the updated packages");

  script_set_attribute(
    attribute:"synopsis", 
    value:"The remote CentOS host is missing one or more security updates."
  );
  script_set_attribute(
    attribute:"description", 
    value:
"Updated python packages that fix several security issues are now
available for Red Hat Enterprise Linux 3 and 4.

This update has been rated as having moderate security impact by the
Red Hat Security Response Team.

Python is an interpreted, interactive, object-oriented programming
language.

An integer overflow flaw was discovered in the way Python's pcre
module handled certain regular expressions. If a Python application
used the pcre module to compile and execute untrusted regular
expressions, it may be possible to cause the application to crash, or
allow arbitrary code execution with the privileges of the Python
interpreter. (CVE-2006-7228)

A flaw was discovered in the strxfrm() function of Python's locale
module. Strings generated by this function were not properly
NULL-terminated. This may possibly cause disclosure of data stored in
the memory of a Python application using this function.
(CVE-2007-2052)

Multiple integer overflow flaws were discovered in Python's imageop
module. If an application written in Python used the imageop module to
process untrusted images, it could cause the application to crash,
enter an infinite loop, or possibly execute arbitrary code with the
privileges of the Python interpreter. (CVE-2007-4965)

Users of Python are advised to upgrade to these updated packages,
which contain backported patches to resolve these issues."
  );
  # http://lists.centos.org/pipermail/centos-announce/2007-December/014491.html
  script_set_attribute(
    attribute:"see_also",
    value:"http://www.nessus.org/u?0cf7614b"
  );
  # http://lists.centos.org/pipermail/centos-announce/2007-December/014493.html
  script_set_attribute(
    attribute:"see_also",
    value:"http://www.nessus.org/u?3b1ef503"
  );
  # http://lists.centos.org/pipermail/centos-announce/2007-December/014496.html
  script_set_attribute(
    attribute:"see_also",
    value:"http://www.nessus.org/u?43c69ff2"
  );
  # http://lists.centos.org/pipermail/centos-announce/2007-December/014497.html
  script_set_attribute(
    attribute:"see_also",
    value:"http://www.nessus.org/u?fc12f42e"
  );
  script_set_attribute(
    attribute:"solution", 
    value:"Update the affected python packages."
  );
  script_set_cvss_base_vector("CVSS2#AV:N/AC:M/Au:N/C:P/I:P/A:P");
  script_set_cvss_temporal_vector("CVSS2#E:ND/RL:OF/RC:C");
  script_set_attribute(attribute:"exploitability_ease", value:"No known exploits are available");
  script_set_attribute(attribute:"exploit_available", value:"false");
  script_cwe_id(189);

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:python");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:python-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:python-docs");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:python-tools");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:centos:centos:tkinter");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:centos:centos:3");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:centos:centos:4");

  script_set_attribute(attribute:"patch_publication_date", value:"2007/12/10");
  script_set_attribute(attribute:"plugin_publication_date", value:"2007/12/11");
  script_set_attribute(attribute:"vuln_publication_date", value:"2007/03/31");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_copyright(english:"This script is Copyright (C) 2007-2015 Tenable Network Security, Inc.");
  script_family(english:"CentOS Local Security Checks");

  script_dependencies("ssh_get_info.nasl");
  script_require_keys("Host/local_checks_enabled", "Host/CentOS/release", "Host/CentOS/rpm-list");

  exit(0);
}


include("audit.inc");
include("global_settings.inc");
include("rpm.inc");


if (!get_kb_item("Host/local_checks_enabled")) audit(AUDIT_LOCAL_CHECKS_NOT_ENABLED);
if (!get_kb_item("Host/CentOS/release")) audit(AUDIT_OS_NOT, "CentOS");
if (!get_kb_item("Host/CentOS/rpm-list")) audit(AUDIT_PACKAGE_LIST_MISSING);


cpu = get_kb_item("Host/cpu");
if (isnull(cpu)) audit(AUDIT_UNKNOWN_ARCH);
if ("x86_64" >!< cpu && "ia64" >!< cpu && cpu !~ "^i[3-6]86$") audit(AUDIT_LOCAL_CHECKS_NOT_IMPLEMENTED, "CentOS", cpu);


flag = 0;
if (rpm_check(release:"CentOS-3", reference:"python-2.2.3-6.8")) flag++;
if (rpm_check(release:"CentOS-3", reference:"python-devel-2.2.3-6.8")) flag++;
if (rpm_check(release:"CentOS-3", reference:"python-docs-2.2.3-6.8")) flag++;
if (rpm_check(release:"CentOS-3", reference:"python-tools-2.2.3-6.8")) flag++;
if (rpm_check(release:"CentOS-3", reference:"tkinter-2.2.3-6.8")) flag++;

if (rpm_check(release:"CentOS-4", cpu:"ia64", reference:"python-2.3.4-14.4.c4.1")) flag++;
if (rpm_check(release:"CentOS-4", cpu:"ia64", reference:"python-devel-2.3.4-14.4.c4.1")) flag++;
if (rpm_check(release:"CentOS-4", cpu:"ia64", reference:"python-docs-2.3.4-14.4.c4.1")) flag++;
if (rpm_check(release:"CentOS-4", cpu:"ia64", reference:"python-tools-2.3.4-14.4.c4.1")) flag++;
if (rpm_check(release:"CentOS-4", cpu:"ia64", reference:"tkinter-2.3.4-14.4.c4.1")) flag++;


if (flag)
{
  if (report_verbosity > 0) security_warning(port:0, extra:rpm_report_get());
  else security_warning(0);
  exit(0);
}
else audit(AUDIT_HOST_NOT, "affected");
