###
# -*- Fundamental -*-
#
# (C) Tenable Network Security, Inc.
#
# This script is released under one of the Tenable Script Licenses and may not
# be used from within scripts released under another license without the
# authorization from Tenable Network Security, Inc.
#
# @NOGPL@
#
# cisco_ios.inc
# $Revision: 1.3 $
#
# This include file is deprecated
###

##
# This function is a placeholder and does not do anything
##
function cisco_func_deprecated() { return 0;}
