#
# (C) Tenable Network Security, Inc.
#
# The descriptive text and package checks in this plugin were  
# extracted from Debian Security Advisory DSA-3207. The text 
# itself is copyright (C) Software in the Public Interest, Inc.
#

include("compat.inc");

if (description)
{
  script_id(82304);
  script_version("$Revision: 1.3 $");
  script_cvs_date("$Date: 2015/04/02 13:36:27 $");

  script_cve_id("CVE-2015-2684");
  script_bugtraq_id(73314);
  script_xref(name:"DSA", value:"3207");

  script_name(english:"Debian DSA-3207-1 : shibboleth-sp2 - security update");
  script_summary(english:"Checks dpkg output for the updated package");

  script_set_attribute(
    attribute:"synopsis", 
    value:"The remote Debian host is missing a security-related update."
  );
  script_set_attribute(
    attribute:"description", 
    value:
"A denial of service vulnerability was found in the Shibboleth (an
federated identity framework) Service Provider. When processing
certain malformed SAML message generated by an authenticated attacker,
the daemon could crash."
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://packages.debian.org/source/wheezy/shibboleth-sp2"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"http://www.debian.org/security/2015/dsa-3207"
  );
  script_set_attribute(
    attribute:"solution", 
    value:
"Upgrade the shibboleth-sp2 packages.

For the stable distribution (wheezy), this problem has been fixed in
version 2.4.3+dfsg-5+deb7u1.

For the upcoming stable distribution (jessie), this problem has been
fixed in version 2.5.3+dfsg-2."
  );
  script_set_cvss_base_vector("CVSS2#AV:N/AC:L/Au:S/C:N/I:N/A:P");
  script_set_cvss_temporal_vector("CVSS2#E:ND/RL:OF/RC:C");
  script_set_attribute(attribute:"exploitability_ease", value:"Exploits are available");
  script_set_attribute(attribute:"exploit_available", value:"true");

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:debian:debian_linux:shibboleth-sp2");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:debian:debian_linux:7.0");

  script_set_attribute(attribute:"patch_publication_date", value:"2015/03/28");
  script_set_attribute(attribute:"plugin_publication_date", value:"2015/03/30");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_copyright(english:"This script is Copyright (C) 2015 Tenable Network Security, Inc.");
  script_family(english:"Debian Local Security Checks");

  script_dependencies("ssh_get_info.nasl");
  script_require_keys("Host/local_checks_enabled", "Host/Debian/release", "Host/Debian/dpkg-l");

  exit(0);
}


include("audit.inc");
include("debian_package.inc");


if (!get_kb_item("Host/local_checks_enabled")) audit(AUDIT_LOCAL_CHECKS_NOT_ENABLED);
if (!get_kb_item("Host/Debian/release")) audit(AUDIT_OS_NOT, "Debian");
if (!get_kb_item("Host/Debian/dpkg-l")) audit(AUDIT_PACKAGE_LIST_MISSING);


flag = 0;
if (deb_check(release:"7.0", prefix:"libapache2-mod-shib2", reference:"2.4.3+dfsg-5+deb7u1")) flag++;
if (deb_check(release:"7.0", prefix:"libshibsp-dev", reference:"2.4.3+dfsg-5+deb7u1")) flag++;
if (deb_check(release:"7.0", prefix:"libshibsp-doc", reference:"2.4.3+dfsg-5+deb7u1")) flag++;
if (deb_check(release:"7.0", prefix:"libshibsp5", reference:"2.4.3+dfsg-5+deb7u1")) flag++;
if (deb_check(release:"7.0", prefix:"shibboleth-sp2-schemas", reference:"2.4.3+dfsg-5+deb7u1")) flag++;

if (flag)
{
  if (report_verbosity > 0) security_warning(port:0, extra:deb_report_get());
  else security_warning(0);
  exit(0);
}
else audit(AUDIT_HOST_NOT, "affected");
