#TRUSTED 60f25af78e7055ce57b791ba3e575ea5406b545b13e074adb1bd25190cf55d5d611116248a1983a02cc4de8a5bfc74397916cd81176d3b720a0aacbd19dac5cd2c0fdbe3f4ead7405241ffd476bb209518ca62df24e1a504bd8ea23cd7f3d38567a1095259f4a373172dc4f0116394c80ee39d96c67704c7a94ad072cf51b23e7d3fe2d4b71a70d48fd8c6cf54796427f572649e72fe3032d9e06c0657981ba3a4c29ae1fcff4d6cd969345fbabf549a4b1e1ae2ffbb717659394226f88725d0d3e791a84fefcb6636019816614e6facd0274bdaa81e18d9072134473e0d06b1b38acfb54babf18147ba1473a4edb03fc2fe261cd4df6b7e91c2eb9e545bbb24cf609cdebfad352f1418edcc845d57722ba79e7b9fb8437bd11ba18ae8fa068c338182f8f21cd6f99a32fb240494bea8c0df7e4c9bcdd034a76633106ebdc6d5e21b58dc8c57e3adff891c8d66a2ba65cad6054973f8d1b5d84b064b31bfa0d17bd6cf137efa73c8dcb372f519cd8a4b85846d6278fc898f40bb6be78fedb3e434eb86aff87df90bd421bd19edbbd87e1e6f94cfaa05fa1d369f654015f7a5a17f452ca13511a81e4ee8f624362b930042a477e3311c3800f66d10e9539c30f36c15332acb34467d952431731fd134e5324a831a83f323576d028352673755bb99285a40e11aa8eee441ba8ffd2e678ff3a8fc2208ba0f48b06101846a5dcfa3

#
# (C) Tenable Network Security, Inc.
#

include("compat.inc");

if (description)
{
  script_id(84239);

  script_version("1.4");
  script_set_attribute(attribute:"plugin_modification_date", value: "2016/09/06");

  script_name(english:"Debugging Log Report");
  script_summary(english:"Aggregates plugin debugging messages.");

  script_set_attribute(attribute:"synopsis", value:
"This plugin gathers the logs written by other plugins and reports
them.");
  script_set_attribute(attribute:"description", value:
"Logs generated by other plugins are reported by this plugin. Plugin 
debugging must be enabled in the policy in order for this plugin
to run.");
  script_set_attribute(attribute:"solution", value:"n/a");
  script_set_attribute(attribute:"risk_factor", value:"None");

  script_set_attribute(attribute:"plugin_publication_date", value:"2015/06/17");

  script_set_attribute(attribute:"plugin_type", value:"combined");
  script_set_attribute(attribute:"agent", value:"all");
  script_end_attributes();

  script_category(ACT_END);
  script_family(english:"Settings");
  script_copyright(english:"This script is Copyright (C) 2015-2016 Tenable Network Security, Inc.");

  script_require_keys("global_settings/enable_plugin_debugging");
  exit(0);
}

include("misc_func.inc");
include("global_settings.inc");
include("spad_log_func.inc");

get_kb_item_or_exit("global_settings/enable_plugin_debugging");

#increasing the memory limits for MDM debug scans which can be rather large
if (defined_func("set_mem_limits"))
  set_mem_limits(max_alloc_size:256*1024*1024, max_program_size:256*1024*1024);
  
logs = spad_log_get_report_attachments();
if(empty_or_null(logs))
  exit(0,"No log information to report.");

# Dump directly to plug-in output for SC / older versions
if(!defined_func("nasl_level") || nasl_level() < 5200 ||
   !isnull(get_preference("sc_version"))
)
{
  report = 'The following plugin debug log(s) have been appended:\n\n';
  foreach log (logs)
  {
    report += '=====================================================\n';
    report += 'Start log : '+log['name']+'\n';
    report += '=====================================================\n';
    report += log['value'];
    report += '=====================================================\n';
    report += 'End log : '+log['name']+'\n';
    report += '=====================================================\n';
  }
  security_note(port:0,extra:report);
}
else
{
  security_report_with_attachments(
    port        : 0,
    level       : 0,
    extra       : "Plugin debug log(s) have been attached.",
    attachments : logs
  );
}
