#
# (C) Tenable Network Security, Inc.
#

include("compat.inc");

if (description) {
  script_id(18248);
  script_version("$Revision: 1.18 $");

  script_cve_id("CVE-2005-1561", "CVE-2005-1562");
  script_bugtraq_id(13601);
  script_osvdb_id(16501,16502,16503,16504,16505,16506,16510,16511,16512,16513,16514,16515,16516,16517,16518,16519);

  script_name(english:"MaxWebPortal <= 1.35 Multiple Vulnerabilities");
 
 script_set_attribute(attribute:"synopsis", value:
"The remote web server contains an ASP application that is affected by
multiple flaws." );
 script_set_attribute(attribute:"description", value:
"According to its banner, the remote host is running a version of
MaxWebPortal that is prone to multiple cross-site scripting and SQL
injection vulnerabilities.  Exploitation of these flaws may result in
password theft and/or site defacement." );
 script_set_attribute(attribute:"see_also", value:"http://www.hackerscenter.com/archive/view.asp?id=2542" );
 script_set_attribute(attribute:"see_also", value:"http://seclists.org/bugtraq/2005/May/121" );
 script_set_attribute(attribute:"solution", value:
"Unknown at this time." );
 script_set_cvss_base_vector("CVSS2#AV:N/AC:L/Au:N/C:P/I:P/A:P");
 script_set_cvss_temporal_vector("CVSS2#E:H/RL:U/RC:ND");
 script_set_attribute(attribute:"exploitability_ease", value:"No exploit is required");
 script_set_attribute(attribute:"exploit_available", value:"true");
 script_cwe_id(20, 74, 79, 442, 629, 711, 712, 722, 725, 750, 751, 800, 801, 809, 811, 864, 900, 928, 931, 990);

 script_set_attribute(attribute:"plugin_publication_date", value: "2005/05/12");
 script_set_attribute(attribute:"vuln_publication_date", value: "2005/05/10");
 script_cvs_date("$Date: 2016/10/27 15:03:54 $");
script_set_attribute(attribute:"plugin_type", value:"remote");
script_end_attributes();

  script_summary(english:"Checks for multiple vulnerabilities in MaxWebPortal <= 1.35");
  script_category(ACT_GATHER_INFO);
  script_family(english:"CGI abuses");
  script_copyright(english:"This script is Copyright (C) 2005-2016 Tenable Network Security, Inc.");
  script_dependencies("http_version.nasl");
  script_exclude_keys("Settings/disable_cgi_scanning");
  script_require_ports("Services/www", 80);
  script_require_keys("www/ASP");
  exit(0);
}

include("global_settings.inc");
include("misc_func.inc");
include("http.inc");

port = get_http_port(default:80);
if (!can_host_asp(port:port)) exit(0, "The web server on port "+port+" does not support ASP");


# Check various directories for MaxWebPortal.
foreach dir (cgi_dirs()) {
  # Pull up the site info page.
  w = http_send_recv3(method:"GET", item:string(dir, "/site_info.asp"), port:port);
  if (isnull(w)) exit(1, "The web server on port "+port+" did not answer");
  res = w[2];

  # Test the version number.
  #
  # nb: a more complete version number can be found in "site_info.asp".
  if (
    "This page is generated by MaxWebPortal" >< res && 
    egrep(string:res, pattern:'acronym title="Version: 1\\.([0-2]|3[0-5])')
  ) {
    security_hole(port);
    set_kb_item(name: 'www/'+port+'/XSS', value: TRUE);
    set_kb_item(name: 'www/'+port+'/SQLInjection', value: TRUE);
    exit(0);
  }
}
