#
# (C) Tenable Network Security, Inc.
#
# The descriptive text and package checks in this plugin were
# extracted from openSUSE Security Update openSUSE-2017-276.
#
# The text description of this plugin is (C) SUSE LLC.
#

include("compat.inc");

if (description)
{
  script_id(97285);
  script_version("$Revision: 3.1 $");
  script_cvs_date("$Date: 2017/02/21 14:37:43 $");

  script_cve_id("CVE-2015-5191");

  script_name(english:"openSUSE Security Update : open-vm-tools (openSUSE-2017-276)");
  script_summary(english:"Check for the openSUSE-2017-276 patch");

  script_set_attribute(
    attribute:"synopsis", 
    value:"The remote openSUSE host is missing a security update."
  );
  script_set_attribute(
    attribute:"description", 
    value:
"This update for open-vm-tools fixes the following issues :

  - Updated to 10.1.0 stable release (boo#1011057)

  + vmware-namespace-cmd command line utility.

  + gtk3 support

  + Common Agent Framework (CAF)

  + guest authentication with xmlsec1

  + FreeBSD support

  + sub-command to push updated network information to the
    host on demand

  + udev rules for configuring SCSI timeouts in the guest

  + fixes for Ubuntu 16.10

  + Fix for quiesced snapshot failure leaving guest file
    system quiesced (boo#1006796)

  + Fix for CVE-2015-5191 (boo#1007600)

  - Report SLES12-SAP guest OS as SLES12 (boo#1013496)

  - Remove building KMP modules. No longer needed or wanted
    for current releases. User space tool vmhgfs-fuse has
    replaced the need for vmhgfs kernel module.

  - Add udev rule to increase VMware virtual disk timeout
    values (boo#994598) 

  - Fix vmtoolsd init script to run vmtoolsd in background.
    (boo#971031)

  + fix originally done in SLE-11-SP4 code base by
    tcech@suse.cz

  - Added patches for GCC 6 build failure (boo#985110)

  - Update to 10.0.7-gtk3 stable branch

  + add support for gtk3, needed by the dndcp and
    resolutionset plugins

  + remove files generated by autoreconf

  + a few minor build fixes

  - Update fixes copy-n-paste and drag-n-drop regressions
    (boo#978424)

  - Added new vmblock-fuse.service

  - Update to 10.0.7 stable branch

  + Added namespace command line utility
    'vmware-namespace-cmd'.

  - Compile without gtkmm support for SLES12 based
    environments (which do not provide gtkmm2.4)

  - Update to 10.0.5 stable branch

  + [vgauth] fix timestamp check

  + [libresolutionSet.so] Add an error handler to X11
    resolutionSet

  + [vmci.ko] Kill tasklet when unloading vmci module

  + [libvmbackup.so] Quiesced snapshots Skip freezing autofs
    mounts.

  + [vmhgfs.ko] make vmhgfs compatible with Linux kernel 4.2 

  - This update also addresses a suspend with systemd issue
    (boo#913727)"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1006796"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1007600"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1011057"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=1013496"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=913727"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=971031"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=978424"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=985110"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=994598"
  );
  script_set_attribute(
    attribute:"solution", 
    value:"Update the affected open-vm-tools packages."
  );
  script_set_attribute(attribute:"risk_factor", value:"Medium");

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libvmtools-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libvmtools0");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libvmtools0-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:open-vm-tools");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:open-vm-tools-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:open-vm-tools-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:open-vm-tools-desktop");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:open-vm-tools-desktop-debuginfo");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:novell:opensuse:42.1");

  script_set_attribute(attribute:"patch_publication_date", value:"2017/02/18");
  script_set_attribute(attribute:"plugin_publication_date", value:"2017/02/21");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_copyright(english:"This script is Copyright (C) 2017 Tenable Network Security, Inc.");
  script_family(english:"SuSE Local Security Checks");

  script_dependencies("ssh_get_info.nasl");
  script_require_keys("Host/local_checks_enabled", "Host/SuSE/release", "Host/SuSE/rpm-list", "Host/cpu");

  exit(0);
}


include("audit.inc");
include("global_settings.inc");
include("rpm.inc");

if (!get_kb_item("Host/local_checks_enabled")) audit(AUDIT_LOCAL_CHECKS_NOT_ENABLED);
release = get_kb_item("Host/SuSE/release");
if (isnull(release) || release =~ "^(SLED|SLES)") audit(AUDIT_OS_NOT, "openSUSE");
if (release !~ "^(SUSE42\.1)$") audit(AUDIT_OS_RELEASE_NOT, "openSUSE", "42.1", release);
if (!get_kb_item("Host/SuSE/rpm-list")) audit(AUDIT_PACKAGE_LIST_MISSING);

ourarch = get_kb_item("Host/cpu");
if (!ourarch) audit(AUDIT_UNKNOWN_ARCH);
if (ourarch !~ "^(i586|i686|x86_64)$") audit(AUDIT_ARCH_NOT, "i586 / i686 / x86_64", ourarch);

flag = 0;

if ( rpm_check(release:"SUSE42.1", reference:"libvmtools-devel-10.1.0-6.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libvmtools0-10.1.0-6.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libvmtools0-debuginfo-10.1.0-6.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"open-vm-tools-10.1.0-6.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"open-vm-tools-debuginfo-10.1.0-6.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"open-vm-tools-debugsource-10.1.0-6.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"open-vm-tools-desktop-10.1.0-6.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"open-vm-tools-desktop-debuginfo-10.1.0-6.1") ) flag++;

if (flag)
{
  if (report_verbosity > 0) security_warning(port:0, extra:rpm_report_get());
  else security_warning(0);
  exit(0);
}
else
{
  tested = pkg_tests_get();
  if (tested) audit(AUDIT_PACKAGE_NOT_AFFECTED, tested);
  else audit(AUDIT_PACKAGE_NOT_INSTALLED, "libvmtools-devel / libvmtools0 / libvmtools0-debuginfo / etc");
}
