#
# (C) Tenable Network Security, Inc.
#
# The descriptive text and package checks in this plugin were
# extracted from openSUSE Security Update openSUSE-2015-953.
#
# The text description of this plugin is (C) SUSE LLC.
#

include("compat.inc");

if (description)
{
  script_id(87627);
  script_version("$Revision: 2.1 $");
  script_cvs_date("$Date: 2015/12/29 14:44:44 $");

  script_cve_id("CVE-2014-8146", "CVE-2014-8147", "CVE-2015-1284", "CVE-2015-1290", "CVE-2015-1291", "CVE-2015-1292", "CVE-2015-1294");

  script_name(english:"openSUSE Security Update : Qt 5 (openSUSE-2015-953)");
  script_summary(english:"Check for the openSUSE-2015-953 patch");

  script_set_attribute(
    attribute:"synopsis", 
    value:"The remote openSUSE host is missing a security update."
  );
  script_set_attribute(
    attribute:"description", 
    value:
"Qt 5 was updated to the 5.5.1 release to deliver upstream improvements
and fixes to Qt functionality.

The following Security fixes are contained in QtWebEngineCore :

  - ICU: CVE-2014-8146, CVE-2014-8147

  - Blink: CVE-2015-1284, CVE-2015-1291, CVE-2015-1292

  - Skia: CVE-2015-1294

  - V8: CVE-2015-1290

The following packages were rebuilt because they use private headers :

  - calibre

  - fcitx-qt5

  - frameworkintegration

  - kwayland

  - kwin5,

  - lxqt-powermanagement

  - lxqt-qtplugin"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=954149"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.opensuse.org/show_bug.cgi?id=959178"
  );
  script_set_attribute(attribute:"solution", value:"Update the affected Qt 5 packages.");
  script_set_cvss_base_vector("CVSS2#AV:N/AC:L/Au:N/C:P/I:P/A:P");

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:calibre");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:calibre-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:calibre-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:fcitx-qt5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:fcitx-qt5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:fcitx-qt5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:fcitx-qt5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:fcitx-qt5-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:fcitx-qt5-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:frameworkintegration-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:frameworkintegration-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:frameworkintegration-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:frameworkintegration-plugin");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:frameworkintegration-plugin-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:frameworkintegration-plugin-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:frameworkintegration-plugin-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:kwayland");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:kwayland-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:kwayland-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:kwayland-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:kwayland-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:kwayland-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:kwayland-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:kwin5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:kwin5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:kwin5-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:kwin5-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:kwin5-lang");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libKF5Style5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libKF5Style5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libKF5Style5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libKF5Style5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libKF5Style5-lang");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DCollision-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DCollision5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DCollision5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DCollision5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DCollision5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DCore-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DCore5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DCore5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DCore5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DCore5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DInput-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DInput5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DInput5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DInput5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DInput5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DLogic-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DLogic5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DLogic5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DLogic5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DLogic5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DQuick-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DQuick5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DQuick5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DQuick5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DQuick5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DQuickRenderer-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DQuickRenderer5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DQuickRenderer5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DQuickRenderer5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DQuickRenderer5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DRenderer-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DRenderer5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DRenderer5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DRenderer5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt53DRenderer5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Bluetooth5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Bluetooth5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Bluetooth5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Bluetooth5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Bluetooth5-imports");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Bluetooth5-imports-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Bootstrap-devel-static");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Bootstrap-devel-static-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5CLucene5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5CLucene5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5CLucene5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5CLucene5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Compositor5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Compositor5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Compositor5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Compositor5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Concurrent-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Concurrent-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Concurrent5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Concurrent5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Concurrent5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Concurrent5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Core-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Core-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Core-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Core5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Core5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Core5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Core5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5DBus-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5DBus-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5DBus-devel-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5DBus-devel-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5DBus-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5DBus5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5DBus5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5DBus5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5DBus5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Declarative5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Declarative5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Declarative5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Declarative5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Designer5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Designer5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Designer5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Designer5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5DesignerComponents5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5DesignerComponents5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5DesignerComponents5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5DesignerComponents5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Gui-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Gui-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Gui-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Gui5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Gui5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Gui5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Gui5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Help5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Help5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Help5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Help5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Location5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Location5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Location5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Location5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Multimedia5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Multimedia5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Multimedia5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Multimedia5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Network-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Network-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Network-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Network5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Network5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Network5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Network5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Nfc5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Nfc5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Nfc5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Nfc5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Nfc5-imports");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Nfc5-imports-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5OpenGL-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5OpenGL-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5OpenGL-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5OpenGL5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5OpenGL5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5OpenGL5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5OpenGL5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5OpenGLExtensions-devel-static");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5OpenGLExtensions-devel-static-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5PlatformHeaders-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5PlatformSupport-devel-static");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5PlatformSupport-devel-static-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5PlatformSupport-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Positioning5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Positioning5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Positioning5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Positioning5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5PrintSupport-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5PrintSupport-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5PrintSupport-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5PrintSupport5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5PrintSupport5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5PrintSupport5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5PrintSupport5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Script5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Script5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Script5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Script5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sensors5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sensors5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sensors5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sensors5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sensors5-imports");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sensors5-imports-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5SerialPort5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5SerialPort5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5SerialPort5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5SerialPort5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-mysql");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-mysql-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-mysql-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-mysql-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-postgresql");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-postgresql-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-postgresql-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-postgresql-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-sqlite");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-sqlite-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-sqlite-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-sqlite-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-unixODBC");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-unixODBC-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-unixODBC-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Sql5-unixODBC-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Svg5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Svg5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Svg5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Svg5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Test-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Test-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Test-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Test5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Test5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Test5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Test5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WaylandClient5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WaylandClient5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WaylandClient5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WaylandClient5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebChannel5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebChannel5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebChannel5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebChannel5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebChannel5-imports");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebChannel5-imports-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebKit-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebKit5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebKit5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebKit5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebKit5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebKit5-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebKit5-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebKit5-imports");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebKit5-imports-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebKitWidgets-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebKitWidgets-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebKitWidgets-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebKitWidgets5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebKitWidgets5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebKitWidgets5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebKitWidgets5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebSockets5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebSockets5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebSockets5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebSockets5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebSockets5-imports");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5WebSockets5-imports-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Widgets-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Widgets-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Widgets-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Widgets5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Widgets5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Widgets5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Widgets5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5X11Extras5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5X11Extras5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5X11Extras5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5X11Extras5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Xml-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Xml-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Xml5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Xml5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Xml5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5Xml5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5XmlPatterns5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5XmlPatterns5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5XmlPatterns5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQt5XmlPatterns5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQtQuick5");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQtQuick5-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQtQuick5-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libQtQuick5-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-creator");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-creator-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-creator-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-linguist");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-linguist-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-linguist-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qt3d-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qt3d-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qt3d-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qt3d-examples-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qt3d-imports");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qt3d-imports-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qt3d-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtbase-common-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtbase-common-devel-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtbase-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtbase-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtbase-doc-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtbase-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtbase-examples-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtbase-examples-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtbase-examples-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtbase-platformtheme-gtk2");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtbase-platformtheme-gtk2-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtbase-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtconnectivity-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtconnectivity-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtconnectivity-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtconnectivity-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtconnectivity-examples-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtconnectivity-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtconnectivity-tools");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtconnectivity-tools-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtct");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtct-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtct-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtdeclarative-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtdeclarative-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtdeclarative-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtdeclarative-devel-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtdeclarative-devel-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtdeclarative-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtdeclarative-examples-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtdeclarative-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtdeclarative-tools");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtdeclarative-tools-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtdoc");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtgraphicaleffects");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtimageformats");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtimageformats-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtimageformats-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtimageformats-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtimageformats-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtimageformats-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtlocation-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtlocation-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtlocation-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtlocation-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtlocation-examples-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtlocation-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtmultimedia-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtmultimedia-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtmultimedia-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtmultimedia-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtmultimedia-examples-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtmultimedia-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtquick1-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtquick1-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtquick1-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtquick1-devel-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtquick1-devel-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtquick1-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtquick1-examples-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtquick1-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtquickcontrols");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtquickcontrols-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtquickcontrols-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtquickcontrols-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtquickcontrols-examples-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtscript-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtscript-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtscript-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtscript-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtscript-examples-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtscript-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtsensors-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtsensors-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtsensors-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtsensors-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtsensors-examples-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtsensors-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtserialport-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtserialport-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtserialport-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtserialport-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtsvg-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtsvg-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtsvg-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtsvg-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtsvg-examples-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtsvg-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qttools");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qttools-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qttools-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qttools-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qttools-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qttools-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qttools-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qttools-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qttools-examples-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qttools-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qttranslations");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwayland");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwayland-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwayland-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwayland-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwayland-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwayland-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwayland-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwayland-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwayland-examples-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwayland-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebchannel-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebchannel-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebchannel-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebchannel-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebchannel-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebengine");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebengine-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebengine-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebengine-debuginfo-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebengine-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebengine-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebengine-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebengine-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebengine-examples-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebengine-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebkit-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebkit-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebkit-examples-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebkit-examples-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebsockets-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebsockets-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebsockets-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebsockets-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtwebsockets-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtx11extras-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtx11extras-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtx11extras-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtxmlpatterns-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtxmlpatterns-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtxmlpatterns-devel-32bit");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtxmlpatterns-examples");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtxmlpatterns-examples-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libqt5-qtxmlpatterns-private-headers-devel");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:lxqt-powermanagement");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:lxqt-powermanagement-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:lxqt-powermanagement-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:lxqt-powermanagement-lang");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:lxqt-qtplugin");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:lxqt-qtplugin-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:lxqt-qtplugin-debugsource");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:novell:opensuse:42.1");

  script_set_attribute(attribute:"patch_publication_date", value:"2015/12/26");
  script_set_attribute(attribute:"plugin_publication_date", value:"2015/12/29");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_copyright(english:"This script is Copyright (C) 2015 Tenable Network Security, Inc.");
  script_family(english:"SuSE Local Security Checks");

  script_dependencies("ssh_get_info.nasl");
  script_require_keys("Host/local_checks_enabled", "Host/SuSE/release", "Host/SuSE/rpm-list", "Host/cpu");

  exit(0);
}


include("audit.inc");
include("global_settings.inc");
include("rpm.inc");

if (!get_kb_item("Host/local_checks_enabled")) audit(AUDIT_LOCAL_CHECKS_NOT_ENABLED);
release = get_kb_item("Host/SuSE/release");
if (isnull(release) || release =~ "^(SLED|SLES)") audit(AUDIT_OS_NOT, "openSUSE");
if (release !~ "^(SUSE42\.1)$") audit(AUDIT_OS_RELEASE_NOT, "openSUSE", "42.1", release);
if (!get_kb_item("Host/SuSE/rpm-list")) audit(AUDIT_PACKAGE_LIST_MISSING);

ourarch = get_kb_item("Host/cpu");
if (!ourarch) audit(AUDIT_UNKNOWN_ARCH);
if (ourarch !~ "^(i586|i686|x86_64)$") audit(AUDIT_ARCH_NOT, "i586 / i686 / x86_64", ourarch);

flag = 0;

if ( rpm_check(release:"SUSE42.1", reference:"calibre-2.46.0-11.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"calibre-debuginfo-2.46.0-11.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"calibre-debugsource-2.46.0-11.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"fcitx-qt5-1.0.4-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"fcitx-qt5-debuginfo-1.0.4-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"fcitx-qt5-debugsource-1.0.4-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"fcitx-qt5-devel-1.0.4-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"frameworkintegration-debugsource-5.16.0-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"frameworkintegration-devel-5.16.0-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"frameworkintegration-plugin-5.16.0-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"frameworkintegration-plugin-debuginfo-5.16.0-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"kwayland-5.4.3-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"kwayland-debuginfo-5.4.3-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"kwayland-debugsource-5.4.3-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"kwayland-devel-5.4.3-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"kwin5-5.4.3-6.10") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"kwin5-debuginfo-5.4.3-6.10") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"kwin5-debugsource-5.4.3-6.10") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"kwin5-devel-5.4.3-6.10") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"kwin5-lang-5.4.3-6.10") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libKF5Style5-5.16.0-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libKF5Style5-debuginfo-5.16.0-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libKF5Style5-lang-5.16.0-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DCollision-devel-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DCollision5-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DCollision5-debuginfo-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DCore-devel-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DCore5-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DCore5-debuginfo-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DInput-devel-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DInput5-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DInput5-debuginfo-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DLogic-devel-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DLogic5-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DLogic5-debuginfo-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DQuick-devel-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DQuick5-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DQuick5-debuginfo-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DQuickRenderer-devel-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DQuickRenderer5-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DQuickRenderer5-debuginfo-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DRenderer-devel-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DRenderer5-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt53DRenderer5-debuginfo-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Bluetooth5-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Bluetooth5-debuginfo-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Bluetooth5-imports-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Bluetooth5-imports-debuginfo-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Bootstrap-devel-static-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5CLucene5-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5CLucene5-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Compositor5-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Compositor5-debuginfo-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Concurrent-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Concurrent5-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Concurrent5-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Core-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Core-private-headers-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Core5-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Core5-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5DBus-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5DBus-devel-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5DBus-private-headers-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5DBus5-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5DBus5-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Declarative5-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Declarative5-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Designer5-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Designer5-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5DesignerComponents5-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5DesignerComponents5-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Gui-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Gui-private-headers-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Gui5-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Gui5-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Help5-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Help5-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Location5-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Location5-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Multimedia5-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Multimedia5-debuginfo-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Network-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Network-private-headers-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Network5-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Network5-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Nfc5-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Nfc5-debuginfo-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Nfc5-imports-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Nfc5-imports-debuginfo-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5OpenGL-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5OpenGL-private-headers-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5OpenGL5-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5OpenGL5-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5OpenGLExtensions-devel-static-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5PlatformHeaders-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5PlatformSupport-devel-static-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5PlatformSupport-private-headers-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Positioning5-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Positioning5-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5PrintSupport-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5PrintSupport-private-headers-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5PrintSupport5-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5PrintSupport5-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Script5-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Script5-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Sensors5-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Sensors5-debuginfo-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Sensors5-imports-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Sensors5-imports-debuginfo-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5SerialPort5-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5SerialPort5-debuginfo-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Sql-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Sql-private-headers-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Sql5-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Sql5-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Sql5-mysql-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Sql5-mysql-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Sql5-postgresql-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Sql5-postgresql-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Sql5-sqlite-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Sql5-sqlite-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Sql5-unixODBC-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Sql5-unixODBC-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Svg5-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Svg5-debuginfo-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Test-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Test-private-headers-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Test5-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Test5-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WaylandClient5-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WaylandClient5-debuginfo-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebChannel5-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebChannel5-debuginfo-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebChannel5-imports-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebChannel5-imports-debuginfo-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebKit-private-headers-devel-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebKit5-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebKit5-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebKit5-devel-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebKit5-imports-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebKit5-imports-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebKitWidgets-devel-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebKitWidgets-private-headers-devel-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebKitWidgets5-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebKitWidgets5-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebSockets5-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebSockets5-debuginfo-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebSockets5-imports-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5WebSockets5-imports-debuginfo-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Widgets-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Widgets-private-headers-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Widgets5-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Widgets5-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5X11Extras5-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5X11Extras5-debuginfo-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Xml-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Xml5-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5Xml5-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5XmlPatterns5-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQt5XmlPatterns5-debuginfo-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQtQuick5-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libQtQuick5-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-creator-3.5.1-6.6") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-creator-debuginfo-3.5.1-6.6") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-creator-debugsource-3.5.1-6.6") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-linguist-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-linguist-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-linguist-devel-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qt3d-debugsource-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qt3d-devel-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qt3d-examples-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qt3d-examples-debuginfo-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qt3d-imports-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qt3d-imports-debuginfo-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qt3d-private-headers-devel-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtbase-common-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtbase-common-devel-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtbase-debugsource-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtbase-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtbase-doc-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtbase-examples-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtbase-examples-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtbase-platformtheme-gtk2-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtbase-platformtheme-gtk2-debuginfo-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtbase-private-headers-devel-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtconnectivity-debugsource-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtconnectivity-devel-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtconnectivity-examples-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtconnectivity-examples-debuginfo-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtconnectivity-private-headers-devel-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtconnectivity-tools-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtconnectivity-tools-debuginfo-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtct-0.20-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtct-debuginfo-0.20-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtct-debugsource-0.20-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtdeclarative-debugsource-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtdeclarative-devel-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtdeclarative-devel-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtdeclarative-examples-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtdeclarative-examples-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtdeclarative-private-headers-devel-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtdeclarative-tools-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtdeclarative-tools-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtdoc-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtgraphicaleffects-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtimageformats-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtimageformats-debuginfo-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtimageformats-debugsource-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtimageformats-devel-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtlocation-debugsource-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtlocation-devel-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtlocation-examples-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtlocation-examples-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtlocation-private-headers-devel-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtmultimedia-debugsource-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtmultimedia-devel-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtmultimedia-examples-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtmultimedia-examples-debuginfo-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtmultimedia-private-headers-devel-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtquick1-debugsource-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtquick1-devel-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtquick1-devel-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtquick1-examples-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtquick1-examples-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtquick1-private-headers-devel-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtquickcontrols-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtquickcontrols-debuginfo-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtquickcontrols-debugsource-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtquickcontrols-examples-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtquickcontrols-examples-debuginfo-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtscript-debugsource-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtscript-devel-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtscript-examples-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtscript-examples-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtscript-private-headers-devel-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtsensors-debugsource-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtsensors-devel-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtsensors-examples-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtsensors-examples-debuginfo-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtsensors-private-headers-devel-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtserialport-debugsource-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtserialport-devel-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtserialport-private-headers-devel-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtsvg-debugsource-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtsvg-devel-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtsvg-examples-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtsvg-examples-debuginfo-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtsvg-private-headers-devel-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qttools-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qttools-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qttools-debugsource-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qttools-devel-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qttools-examples-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qttools-examples-debuginfo-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qttools-private-headers-devel-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qttranslations-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwayland-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwayland-debuginfo-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwayland-debugsource-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwayland-devel-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwayland-examples-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwayland-examples-debuginfo-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwayland-private-headers-devel-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebchannel-debugsource-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebchannel-devel-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebchannel-examples-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebchannel-private-headers-devel-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebengine-5.5.1-4.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebengine-debuginfo-5.5.1-4.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebengine-debugsource-5.5.1-4.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebengine-devel-5.5.1-4.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebengine-examples-5.5.1-4.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebengine-examples-debuginfo-5.5.1-4.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebengine-private-headers-devel-5.5.1-4.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebkit-debugsource-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebkit-examples-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebkit-examples-debuginfo-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebkit-examples-debugsource-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebsockets-debugsource-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebsockets-devel-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebsockets-examples-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtwebsockets-private-headers-devel-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtx11extras-debugsource-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtx11extras-devel-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtxmlpatterns-debugsource-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtxmlpatterns-devel-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtxmlpatterns-examples-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtxmlpatterns-examples-debuginfo-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"libqt5-qtxmlpatterns-private-headers-devel-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"lxqt-powermanagement-0.9.0-4.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"lxqt-powermanagement-debuginfo-0.9.0-4.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"lxqt-powermanagement-debugsource-0.9.0-4.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"lxqt-powermanagement-lang-0.9.0-4.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"lxqt-qtplugin-0.9.0-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"lxqt-qtplugin-debuginfo-0.9.0-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", reference:"lxqt-qtplugin-debugsource-0.9.0-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"fcitx-qt5-32bit-1.0.4-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"fcitx-qt5-debuginfo-32bit-1.0.4-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"frameworkintegration-devel-32bit-5.16.0-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"frameworkintegration-plugin-32bit-5.16.0-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"frameworkintegration-plugin-debuginfo-32bit-5.16.0-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"kwayland-32bit-5.4.3-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"kwayland-debuginfo-32bit-5.4.3-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"kwayland-devel-32bit-5.4.3-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libKF5Style5-32bit-5.16.0-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libKF5Style5-debuginfo-32bit-5.16.0-6.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt53DCollision5-32bit-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt53DCollision5-debuginfo-32bit-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt53DCore5-32bit-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt53DCore5-debuginfo-32bit-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt53DInput5-32bit-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt53DInput5-debuginfo-32bit-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt53DLogic5-32bit-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt53DLogic5-debuginfo-32bit-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt53DQuick5-32bit-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt53DQuick5-debuginfo-32bit-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt53DQuickRenderer5-32bit-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt53DQuickRenderer5-debuginfo-32bit-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt53DRenderer5-32bit-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt53DRenderer5-debuginfo-32bit-5.5.1-2.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Bluetooth5-32bit-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Bluetooth5-debuginfo-32bit-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Bootstrap-devel-static-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5CLucene5-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5CLucene5-debuginfo-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Compositor5-32bit-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Compositor5-debuginfo-32bit-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Concurrent-devel-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Concurrent5-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Concurrent5-debuginfo-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Core-devel-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Core5-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Core5-debuginfo-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5DBus-devel-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5DBus-devel-debuginfo-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5DBus5-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5DBus5-debuginfo-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Declarative5-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Declarative5-debuginfo-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Designer5-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Designer5-debuginfo-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5DesignerComponents5-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5DesignerComponents5-debuginfo-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Gui-devel-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Gui5-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Gui5-debuginfo-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Help5-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Help5-debuginfo-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Location5-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Location5-debuginfo-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Multimedia5-32bit-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Multimedia5-debuginfo-32bit-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Network-devel-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Network5-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Network5-debuginfo-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Nfc5-32bit-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Nfc5-debuginfo-32bit-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5OpenGL-devel-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5OpenGL5-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5OpenGL5-debuginfo-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5OpenGLExtensions-devel-static-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5PlatformSupport-devel-static-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Positioning5-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Positioning5-debuginfo-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5PrintSupport-devel-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5PrintSupport5-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5PrintSupport5-debuginfo-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Script5-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Script5-debuginfo-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Sensors5-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Sensors5-debuginfo-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5SerialPort5-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5SerialPort5-debuginfo-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Sql-devel-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Sql5-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Sql5-debuginfo-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Sql5-mysql-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Sql5-mysql-debuginfo-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Sql5-postgresql-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Sql5-postgresql-debuginfo-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Sql5-sqlite-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Sql5-sqlite-debuginfo-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Sql5-unixODBC-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Sql5-unixODBC-debuginfo-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Svg5-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Svg5-debuginfo-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Test-devel-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Test5-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Test5-debuginfo-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5WaylandClient5-32bit-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5WaylandClient5-debuginfo-32bit-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5WebChannel5-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5WebChannel5-debuginfo-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5WebKit5-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5WebKit5-debuginfo-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5WebKit5-devel-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5WebKitWidgets-devel-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5WebKitWidgets5-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5WebKitWidgets5-debuginfo-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5WebSockets5-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5WebSockets5-debuginfo-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Widgets-devel-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Widgets5-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Widgets5-debuginfo-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5X11Extras5-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5X11Extras5-debuginfo-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Xml-devel-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Xml5-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5Xml5-debuginfo-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5XmlPatterns5-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQt5XmlPatterns5-debuginfo-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQtQuick5-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libQtQuick5-debuginfo-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtbase-examples-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtbase-examples-debuginfo-32bit-5.5.1-4.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtconnectivity-devel-32bit-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtdeclarative-devel-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtdeclarative-devel-debuginfo-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtimageformats-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtimageformats-debuginfo-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtlocation-devel-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtmultimedia-devel-32bit-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtquick1-devel-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtquick1-devel-debuginfo-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtscript-devel-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtsensors-devel-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtserialport-devel-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtsvg-devel-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qttools-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qttools-debuginfo-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qttools-devel-32bit-5.5.1-3.2") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtwayland-32bit-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtwayland-debuginfo-32bit-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtwayland-devel-32bit-5.5.1-3.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtwebchannel-devel-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtwebengine-32bit-5.5.1-4.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtwebengine-debuginfo-32bit-5.5.1-4.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtwebengine-devel-32bit-5.5.1-4.3") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtwebsockets-devel-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtx11extras-devel-32bit-5.5.1-3.1") ) flag++;
if ( rpm_check(release:"SUSE42.1", cpu:"x86_64", reference:"libqt5-qtxmlpatterns-devel-32bit-5.5.1-3.1") ) flag++;

if (flag)
{
  if (report_verbosity > 0) security_hole(port:0, extra:rpm_report_get());
  else security_hole(0);
  exit(0);
}
else
{
  tested = pkg_tests_get();
  if (tested) audit(AUDIT_PACKAGE_NOT_AFFECTED, tested);
  else audit(AUDIT_PACKAGE_NOT_INSTALLED, "calibre / calibre-debuginfo / calibre-debugsource / fcitx-qt5 / etc");
}
