#
# (C) Tenable Network Security, Inc.
#
# The descriptive text and package checks in this plugin were
# extracted from openSUSE Security Update openSUSE-2012-187.
#
# The text description of this plugin is (C) SUSE LLC.
#

include("compat.inc");

if (description)
{
  script_id(74584);
  script_version("$Revision: 1.1 $");
  script_cvs_date("$Date: 2014/06/13 20:53:55 $");

  script_cve_id("CVE-2012-0037");
  script_osvdb_id(80307);

  script_name(english:"openSUSE Security Update : libreoffice (openSUSE-SU-2012:0433-1)");
  script_summary(english:"Check for the openSUSE-2012-187 patch");

  script_set_attribute(
    attribute:"synopsis", 
    value:"The remote openSUSE host is missing a security update."
  );
  script_set_attribute(
    attribute:"description", 
    value:
"  - updated to libreoffice-3.4.5.4 (SUSE 3.4.5-rc2)

  - calc

  - pie charts colors messed in XLS import (fdo#40320)

  - correctly import data point formats in data series
    (fdo#40320)

  - components

  - crash when parsing XML signatures (fdo#39657)

  - broken getDataArray (fdo#46165, fdo#38441, i#117010)

  - don't paint a frame around the list of edit boxes
    (fdo#42543)

  - inconsistent compression method for encrypted documents
    (bnc#653688)

  - filters

  - more on bentConnectors (bnc#736495)

  - wrong text color in smartArt (bnc#746996)

  - reading of w:textbox contents (bnc#693388)

  - textbox position and size DOCX import (fdo#45560)

  - RTF/DOCX import of transparent frames (bnc#695479)

  - consecutive frames in RTF/DOCX import (bnc#703032)

  - handling of frame properties in RTF import (bnc#417818)

  - force imported XLSX active tab to be shown (bnc#748198)

  - create TableManager for inside shapes (bnc#747471,
    bnc#693238)

  - textboxes import with OLE objects inside (bnc#747471,
    bnc#693238)

  - impress

  - do not create an empty slide when printing handouts
    (fdo#31966)

  - libs-core

  - default shortcut for .uno:SearchDialog should be Ctrl+H

  - crash using instances dialog of dataform navigator
    (fdo#44816)

  - libs-extern

  - disable problematic reading of external entities in
    raptor

  - libs-gui

  - correctly calculate leap year

  - use proper Indian Rupee currency symbol U+20B9
    (rh#794679)

  - writer

  - field refreshing (fdo#39694)

  - more layout crashers (i#101776, fdo#39510)

  - textbox borders style and width in DOCX import
    (fdo#45560)

  - expand all text fields when setting properties
    (fdo#42073)

  - updated to libreoffice-3.4.5.3 (SUSE 3.4.5-rc1)

  - version 3.4.5.3, tag suse-3.4.5.3 (SUSE LO 3.4.5-rc1)

  - SmartArt import

  - custom shapes import

  - Oracle Java 1.7.0 detection

  - reading AES-encrypted ODF 1.2 documents as generated by
    LO 3.5

  - base

  - iterator misuse (fdo #44040, bnc#742178)

  - calc

  - allow pasting to multiple ranges (bnc#715094)

  - correctly convert chart data ranges (bnc#727504)

  - definedName corruption for XLSX export (bnc#741182)

  - adjust/shrink the ranges while copying (bnc#677811)

  - extra graph data is displayed for label (bnc#717290)

  - getCellRangeByName failure for named range (bnc#738113)

  - graph in XLS file has dates displayed wrong (bnc#720443)

  - improve performance of large Excel documents
    (bnc#715104)

  - display page background color/image properly
    (bnc#722045)

  - pivot table output becoming empty on re-save
    (bnc#715543)

  - encode virtual paths to local volume correctly
    (bnc#719887)

  - avoid adjusting cell-anchored objects on other sheets
    (bnc#726152)

  - make sure to adjust the sheet index of drawing objects
    (bnc#733864)

  - make the data validation popup more reliable (fdo
    #36851, bnc#737190)

  - filters

  - table style (bnc#705991)

  - text rotation fixes (bnc#734734)

  - crash in PPTX import (bnc#706792)

  - read w:sdt* contents (bnc#705949)

  - connector shape fixes (bnc#719989)

  - legacy fragment import (bnc#699334)

  - non-working Excel macros (bnc#705977)

  - free drawn curves import (bnc#657909)

  - group shape transformations (bnc#621739)

  - extLst of drawings in diagrams import (bnc#655408)

  - flip properties of custom shapes import (bnc#705985)

  - line spacing is used from previous values (bnc#734734)

  - missing ooxml customshape->mso shape name entries
    (bnc#737921)

  - word doesn't break the numberings and prefers hiding
    them (bnc#707157)

  - impress

  - undo corruption (bnc#685123)

  - do not set duplicate master slide names (bnc#735533)

  - libs-core

  - handle copy and paste from ConsoleOne (bnc#704274)

  - VBA control events not working, broken eventattacher
    (bnc#718227)

  - 'General Error' when double-click graphic in
    presentation (bnc#720948)

  - libs-extern-sys

  - upgrade graphite to 1.0.3 fix surrogate support

  - libs-gui

  - crash at exit (bnc#728603)

  - radial gradient offset (bnc#714787)

  - horizontal scrollbars with KDE oxygen style (bnc#722918)

  - rendering of metafiles embedded in EMF+ (updated)
    (bnc#705956)

  - postprocess

  - make the 3D transitions work again (bnc#728559)

  - ure

  - make Duden Korrektor 5 and 6 work

  - writer

  - frame selection (bnc#740117)

  - crash when editing index (bnc#726174)

  - order database properties (bnc#740032)

  - numbering levels in DOC import (bnc#715115)

  - image size issue in DOC import (bnc#718971)

  - pointless forward moving of a table (bnc#706138)

  - tabs set after the end margin in DOCX import
    (bnc#693238)

  - add hyperlinks by default in Table of Contents
    (bnc#705956)

  - updated to libreoffice-3.4.4.3 (SUSE 3.4.4-rc1 == 
final) :

  - base

  - crash when inserting a constant in a query (fdo#38286)

  - calc

  - crash when modifying a named range

  - speed up range name lookup by index (bnc#715104)

  - recalculate matrix formula dimension correctly
    (fdo#39485)

  - mark all formula cells dirty when appending a new sheet
    (fdo#35965)

  - components

  - handling of SAFEARRAY(s) in olebridge (fdo#38441)

  - filters

  - auto fit text VIEWING too small in PPT import
    (fdo#41245)

  - impress

  - hang in slideshow (fdo#32861)

  - crash while dropping texture (fdo#38391)

  - libs-core

  - recognize .svg in ODF container (fdo#41995)

  - dictionaries lost after LibO upgrade (fdo#37195)

  - crash when 'Find Record' button is clicked in Base
    (fdo#40701)

  - fix the drawing of dotted and dashed borders in Calc
    (fdo#37129)

  - VBA control events not working; broken eventattacher
    (bnc#718227)

  - libs-extern-sys

  - upgrade graphite to 1.0.3 to fix surrogate support

  - libs-gui

  - crash when changing screen resolution

  - let Qt call XInitThreads() (fdo#40298)

  - activation order crashes address database (fdo#41022)

  - drawing of dotted and dashed borders in Calc (fdo#37129)

  - translations

  - update translations

  - writer

  - leak in PDF export (i#116448)

  - crash when editing index (bnc#726174)

  - crash while processing incorrect range of pages
    (fdo#35513)

  - crash on closing document with footnotes (fdo#39510,
    lp#854626)"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"http://lists.opensuse.org/opensuse-updates/2012-03/msg00052.html"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"http://openoffice.org/bugzilla/show_bug.cgi?id=101776"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"http://openoffice.org/bugzilla/show_bug.cgi?id=116448"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"http://openoffice.org/bugzilla/show_bug.cgi?id=117010"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=31966"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=32861"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=35513"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=35965"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=37129"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=37195"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=38286"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=38391"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=38441"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=39485"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=39510"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=39657"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=39694"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=40298"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=40320"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=40461"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=40701"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=41022"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=41245"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=41681"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=41995"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=42073"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=42543"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=44816"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=45560"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=46165"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.freedesktop.org/show_bug.cgi?id=46337"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugs.launchpad.net/bugs/854626"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=417818"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=621739"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=653688"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=655408"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=657909"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=677811"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=685123"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=693238"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=693388"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=695479"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=699334"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=703032"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=704274"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=705949"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=705956"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=705977"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=705985"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=705991"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=706138"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=706792"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=707157"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=714787"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=715094"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=715104"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=715115"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=715543"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=717290"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=718227"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=718694"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=718971"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=719656"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=719887"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=719989"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=720443"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=720948"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=722045"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=722644"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=722918"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=723074"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=724087"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=726152"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=726174"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=727504"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=728559"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=728603"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=733864"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=734734"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=734781"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=735533"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=736495"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=737190"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=737921"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=738113"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=740032"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=740117"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=740453"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=741043"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=741182"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=742178"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=746996"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=747471"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=748198"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.novell.com/show_bug.cgi?id=748548"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.redhat.com/show_bug.cgi?id=667082"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.redhat.com/show_bug.cgi?id=794679"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://features.opensuse.org/312645"
  );
  script_set_attribute(
    attribute:"solution", 
    value:"Update the affected libreoffice packages."
  );
  script_set_cvss_base_vector("CVSS2#AV:N/AC:M/Au:N/C:P/I:N/A:N");

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-base");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-base-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-base-drivers-mysql");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-base-drivers-mysql-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-base-drivers-postgresql");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-base-drivers-postgresql-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-base-extensions");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-branding-upstream");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-calc");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-calc-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-calc-extensions");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-draw");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-draw-extensions");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-draw-extensions-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-filters-optional");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-filters-optional-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-gnome");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-gnome-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-cs");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-da");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-de");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-en-GB");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-en-US");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-en-ZA");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-es");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-et");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-fr");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-gl");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-gu-IN");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-hi-IN");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-hu");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-it");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-ja");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-km");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-ko");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-nl");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-pl");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-pt");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-pt-BR");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-ru");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-sl");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-sv");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-zh-CN");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-help-zh-TW");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-icon-theme-crystal");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-icon-theme-galaxy");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-icon-theme-hicontrast");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-icon-theme-oxygen");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-icon-theme-tango");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-icon-themes-prebuilt");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-impress");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-impress-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-impress-extensions");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-impress-extensions-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-kde");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-kde-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-kde4");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-kde4-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-af");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-ar");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-be-BY");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-bg");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-br");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-ca");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-cs");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-cy");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-da");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-de");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-el");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-en-GB");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-en-ZA");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-es");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-et");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-fi");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-fr");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-ga");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-gl");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-gu-IN");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-he");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-hi-IN");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-hr");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-hu");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-it");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-ja");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-ka");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-km");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-ko");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-lt");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-mk");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-nb");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-nl");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-nn");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-nr");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-pa-IN");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-pl");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-prebuilt");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-pt");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-pt-BR");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-ru");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-rw");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-sh");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-sk");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-sl");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-sr");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-ss");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-st");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-sv");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-tg");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-th");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-tr");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-ts");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-uk");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-ve");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-vi");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-xh");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-zh-CN");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-zh-TW");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-l10n-zu");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-mailmerge");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-math");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-math-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-officebean");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-officebean-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-pyuno");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-pyuno-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-sdk");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-sdk-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-testtool");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-testtool-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-writer");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-writer-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:opensuse:libreoffice-writer-extensions");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:novell:opensuse:11.4");

  script_set_attribute(attribute:"patch_publication_date", value:"2012/03/29");
  script_set_attribute(attribute:"plugin_publication_date", value:"2014/06/13");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_copyright(english:"This script is Copyright (C) 2014 Tenable Network Security, Inc.");
  script_family(english:"SuSE Local Security Checks");

  script_dependencies("ssh_get_info.nasl");
  script_require_keys("Host/local_checks_enabled", "Host/SuSE/release", "Host/SuSE/rpm-list", "Host/cpu");

  exit(0);
}


include("audit.inc");
include("global_settings.inc");
include("rpm.inc");

if (!get_kb_item("Host/local_checks_enabled")) audit(AUDIT_LOCAL_CHECKS_NOT_ENABLED);
release = get_kb_item("Host/SuSE/release");
if (isnull(release) || release =~ "^(SLED|SLES)") audit(AUDIT_OS_NOT, "openSUSE");
if (release !~ "^(SUSE11\.4)$") audit(AUDIT_OS_RELEASE_NOT, "openSUSE", "11.4", release);
if (!get_kb_item("Host/SuSE/rpm-list")) audit(AUDIT_PACKAGE_LIST_MISSING);

ourarch = get_kb_item("Host/cpu");
if (!ourarch) audit(AUDIT_UNKNOWN_ARCH);
if (ourarch !~ "^(i586|i686|x86_64)$") audit(AUDIT_ARCH_NOT, "i586 / i686 / x86_64", ourarch);

flag = 0;

if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-base-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-base-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-base-drivers-mysql-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-base-drivers-mysql-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-base-drivers-postgresql-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-base-drivers-postgresql-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-base-extensions-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-branding-upstream-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-calc-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-calc-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-calc-extensions-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-debugsource-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-draw-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-draw-extensions-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-draw-extensions-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-filters-optional-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-filters-optional-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-gnome-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-gnome-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-cs-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-da-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-de-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-en-GB-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-en-US-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-en-ZA-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-es-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-et-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-fr-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-gl-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-gu-IN-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-hi-IN-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-hu-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-it-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-ja-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-km-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-ko-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-nl-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-pl-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-pt-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-pt-BR-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-ru-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-sl-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-sv-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-zh-CN-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-help-zh-TW-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-icon-theme-crystal-3.4.5.5-14.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-icon-theme-galaxy-3.4.5.5-14.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-icon-theme-hicontrast-3.4.5.5-14.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-icon-theme-oxygen-3.4.5.5-14.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-icon-theme-tango-3.4.5.5-14.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-icon-themes-prebuilt-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-impress-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-impress-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-impress-extensions-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-impress-extensions-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-kde-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-kde-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-kde4-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-kde4-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-af-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-ar-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-be-BY-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-bg-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-br-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-ca-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-cs-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-cy-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-da-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-de-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-el-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-en-GB-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-en-ZA-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-es-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-et-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-fi-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-fr-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-ga-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-gl-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-gu-IN-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-he-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-hi-IN-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-hr-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-hu-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-it-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-ja-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-ka-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-km-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-ko-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-lt-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-mk-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-nb-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-nl-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-nn-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-nr-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-pa-IN-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-pl-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-prebuilt-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-pt-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-pt-BR-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-ru-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-rw-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-sh-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-sk-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-sl-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-sr-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-ss-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-st-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-sv-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-tg-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-th-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-tr-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-ts-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-uk-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-ve-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-vi-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-xh-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-zh-CN-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-zh-TW-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-l10n-zu-3.4.5.5-122.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-mailmerge-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-math-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-math-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-officebean-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-officebean-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-pyuno-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-pyuno-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-sdk-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-sdk-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-testtool-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-testtool-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-writer-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-writer-debuginfo-3.4.5.5-97.1") ) flag++;
if ( rpm_check(release:"SUSE11.4", reference:"libreoffice-writer-extensions-3.4.5.5-97.1") ) flag++;

if (flag)
{
  if (report_verbosity > 0) security_warning(port:0, extra:rpm_report_get());
  else security_warning(0);
  exit(0);
}
else
{
  tested = pkg_tests_get();
  if (tested) audit(AUDIT_PACKAGE_NOT_AFFECTED, tested);
  else audit(AUDIT_PACKAGE_NOT_INSTALLED, "libreoffice-branding-upstream / libreoffice-help-en-US / etc");
}
