#
# (C) Tenable Network Security, Inc.
#
# The descriptive text is (C) Scientific Linux.
#

if (NASL_LEVEL < 3000) exit(0);

include("compat.inc");

if (description)
{
  script_id(61091);
  script_version("$Revision: 1.2 $");
  script_cvs_date("$Date: 2014/08/16 19:47:27 $");

  script_cve_id("CVE-2010-3389");

  script_name(english:"Scientific Linux Security Update : rgmanager on SL5.x i386/x86_64");
  script_summary(english:"Checks rpm output for the updated package");

  script_set_attribute(
    attribute:"synopsis", 
    value:"The remote Scientific Linux host is missing a security update."
  );
  script_set_attribute(
    attribute:"description", 
    value:
"The rgmanager package contains the Resource Group Manager, which
provides the ability to create and manage high-availability server
applications in the event of system downtime.

It was discovered that certain resource agent scripts set the
LD_LIBRARY_PATH environment variable to an insecure value containing
empty path elements. A local user able to trick a user running those
scripts to run them while working from an attacker-writable directory
could use this flaw to escalate their privileges via a specially
crafted dynamic library. (CVE-2010-3389)

This update also fixes the following bugs :

  - The failover domain 'nofailback' option was not honored
    if a service was in the 'starting' state. This bug has
    been fixed.

  - PID files with white spaces in the file name are now
    handled correctly.

  - The /usr/sbin/rhev-check.sh script can now be used from
    within Cron.

  - The clustat utility now reports the correct version.

  - The oracledb.sh agent now attempts to try the 'shutdown
    immediate' command instead of using the 'shutdown abort'
    command.

  - The SAPInstance and SAPDatabase scripts now use proper
    directory name quoting so they no longer collide with
    directory names like '/u'.

  - The clufindhostname utility now returns the correct
    value in all cases.

  - The nfsclient resource agent now handles paths with
    trailing slashes correctly.

  - The last owner of a service is now reported correctly
    after a failover.

  - The /usr/share/cluster/fs.sh script no longer runs the
    'quotaoff' command if quotas were not configured.

  - The 'listen' line in the /etc/httpd/conf/httpd.conf file
    generated by the Apache resource agent is now correct.

  - The tomcat-5 resource agent no longer generates
    incorrect configurations.

  - The time required to stop an NFS resource when the
    server is unavailable has been reduced.

  - When using exclusive prioritization, a higher priority
    service now preempts a lower priority service after
    status check failures.

  - The postgres-8 resource agent now correctly detects
    failed start operations.

  - The handling of reference counts passed by rgmanager to
    resource agents now works properly, as expected.

As well, this update adds the following enhancements :

  - It is now possible to disable updates to static routes
    by the IP resource agent.

  - It is now possible to use XFS as a file system within a
    cluster service.

  - It is now possible to use the 'clustat' command as a
    non-root user, so long as that user is in the 'root'
    group.

  - It is now possible to migrate virtual machines when
    central processing is enabled.

  - The rgmanager init script will now delay after stopping
    services in order to allow time for other nodes to
    restart them.

  - The handling of failed independent subtrees has been
    corrected.

All users of Resource Group Manager are advised to upgrade to this
updated package, which contains backported patches to correct these
issues and add these enhancements."
  );
  # http://listserv.fnal.gov/scripts/wa.exe?A2=ind1108&L=scientific-linux-errata&T=0&P=788
  script_set_attribute(
    attribute:"see_also",
    value:"http://www.nessus.org/u?1e7be2cb"
  );
  script_set_attribute(
    attribute:"solution", 
    value:"Update the affected rgmanager package."
  );
  script_set_cvss_base_vector("CVSS2#AV:L/AC:M/Au:N/C:C/I:C/A:C");

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"x-cpe:/o:fermilab:scientific_linux");

  script_set_attribute(attribute:"patch_publication_date", value:"2011/07/21");
  script_set_attribute(attribute:"plugin_publication_date", value:"2012/08/01");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_copyright(english:"This script is Copyright (C) 2012-2014 Tenable Network Security, Inc.");
  script_family(english:"Scientific Linux Local Security Checks");

  script_dependencies("ssh_get_info.nasl");
  script_require_keys("Host/local_checks_enabled", "Host/cpu", "Host/RedHat/release", "Host/RedHat/rpm-list");

  exit(0);
}


include("audit.inc");
include("global_settings.inc");
include("rpm.inc");


if (!get_kb_item("Host/local_checks_enabled")) audit(AUDIT_LOCAL_CHECKS_NOT_ENABLED);
release = get_kb_item("Host/RedHat/release");
if (isnull(release) || "Scientific Linux " >!< release) audit(AUDIT_HOST_NOT, "running Scientific Linux");
if (!get_kb_item("Host/RedHat/rpm-list")) audit(AUDIT_PACKAGE_LIST_MISSING);

cpu = get_kb_item("Host/cpu");
if (isnull(cpu)) audit(AUDIT_UNKNOWN_ARCH);
if (cpu >!< "x86_64" && cpu !~ "^i[3-6]86$") audit(AUDIT_LOCAL_CHECKS_NOT_IMPLEMENTED, "Scientific Linux", cpu);


flag = 0;
if (rpm_check(release:"SL5", reference:"rgmanager-2.0.52-21.el5")) flag++;


if (flag)
{
  if (report_verbosity > 0) security_warning(port:0, extra:rpm_report_get());
  else security_warning(0);
  exit(0);
}
else audit(AUDIT_HOST_NOT, "affected");
