#
# (C) Tenable Network Security, Inc.
#
# The descriptive text is (C) Scientific Linux.
#

include("compat.inc");

if (description)
{
  script_id(65013);
  script_version("$Revision: 1.1 $");
  script_cvs_date("$Date: 2013/03/05 11:50:59 $");

  script_cve_id("CVE-2012-1182");

  script_name(english:"Scientific Linux Security Update : openchange on SL6.x i386/x86_64");
  script_summary(english:"Checks rpm output for the updated packages");

  script_set_attribute(
    attribute:"synopsis", 
    value:
"The remote Scientific Linux host is missing one or more security
updates."
  );
  script_set_attribute(
    attribute:"description", 
    value:
"A flaw was found in the Samba suite's Perl-based DCE/RPC IDL (PIDL)
compiler. As OpenChange uses code generated by PIDL, this could have
resulted in buffer overflows in the way OpenChange handles RPC calls.
With this update, the code has been generated with an updated version
of PIDL to correct this issue. (CVE-2012-1182)

The openchange packages have been upgraded to upstream version 1.0,
which provides a number of bug fixes and enhancements over the
previous version, including support for the rebased samba4 packages
and several API changes.

This update also fixes the following bugs :

  - When the user tried to modify a meeting with one
    required attendee and himself as the organizer, a
    segmentation fault occurred in the memcpy() function.
    Consequently, the evolution-data-server application
    terminated unexpectedly with a segmentation fault. This
    bug has been fixed and evolution- data-server no longer
    crashes in the described scenario.

  - Prior to this update, OpenChange 1.0 was unable to send
    messages with a large message body or with extensive
    attachment. This was caused by minor issues in
    OpenChange's exchange.idl definitions. This bug has been
    fixed and OpenChange now sends extensive messages
    without complications."
  );
  # http://listserv.fnal.gov/scripts/wa.exe?A2=ind1303&L=scientific-linux-errata&T=0&P=331
  script_set_attribute(
    attribute:"see_also",
    value:"http://www.nessus.org/u?d3eb379e"
  );
  script_set_attribute(attribute:"solution", value:"Update the affected packages.");
  script_set_cvss_base_vector("CVSS2#AV:N/AC:L/Au:N/C:C/I:C/A:C");
  script_set_attribute(attribute:"exploitability_ease", value:"Exploits are available");
  script_set_attribute(attribute:"exploit_available", value:"true");
  script_set_attribute(attribute:"exploit_framework_core", value:"true");
  script_set_attribute(attribute:"metasploit_name", value:'Samba SetInformationPolicy AuditEventsInfo Heap Overflow');
  script_set_attribute(attribute:"exploit_framework_metasploit", value:"true");
  script_set_attribute(attribute:"exploit_framework_canvas", value:"true");
  script_set_attribute(attribute:"canvas_package", value:'CANVAS');

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"x-cpe:/o:fermilab:scientific_linux");

  script_set_attribute(attribute:"patch_publication_date", value:"2013/02/21");
  script_set_attribute(attribute:"plugin_publication_date", value:"2013/03/05");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_copyright(english:"This script is Copyright (C) 2013 Tenable Network Security, Inc.");
  script_family(english:"Scientific Linux Local Security Checks");

  script_dependencies("ssh_get_info.nasl");
  script_require_keys("Host/local_checks_enabled", "Host/cpu", "Host/RedHat/release", "Host/RedHat/rpm-list");

  exit(0);
}


include("audit.inc");
include("global_settings.inc");
include("rpm.inc");


if (!get_kb_item("Host/local_checks_enabled")) audit(AUDIT_LOCAL_CHECKS_NOT_ENABLED);
release = get_kb_item("Host/RedHat/release");
if (isnull(release) || "Scientific Linux " >!< release) audit(AUDIT_HOST_NOT, "running Scientific Linux");
if (!get_kb_item("Host/RedHat/rpm-list")) audit(AUDIT_PACKAGE_LIST_MISSING);

cpu = get_kb_item("Host/cpu");
if (isnull(cpu)) audit(AUDIT_UNKNOWN_ARCH);
if (cpu >!< "x86_64" && cpu !~ "^i[3-6]86$") audit(AUDIT_LOCAL_CHECKS_NOT_IMPLEMENTED, "Scientific Linux", cpu);


flag = 0;
if (rpm_check(release:"SL6", reference:"evolution-mapi-0.28.3-12.el6")) flag++;
if (rpm_check(release:"SL6", reference:"evolution-mapi-debuginfo-0.28.3-12.el6")) flag++;
if (rpm_check(release:"SL6", reference:"evolution-mapi-devel-0.28.3-12.el6")) flag++;
if (rpm_check(release:"SL6", reference:"openchange-1.0-4.el6")) flag++;
if (rpm_check(release:"SL6", reference:"openchange-client-1.0-4.el6")) flag++;
if (rpm_check(release:"SL6", reference:"openchange-debuginfo-1.0-4.el6")) flag++;
if (rpm_check(release:"SL6", reference:"openchange-devel-1.0-4.el6")) flag++;
if (rpm_check(release:"SL6", reference:"openchange-devel-docs-1.0-4.el6")) flag++;


if (flag)
{
  if (report_verbosity > 0) security_hole(port:0, extra:rpm_report_get());
  else security_hole(0);
  exit(0);
}
else audit(AUDIT_HOST_NOT, "affected");
