#
# (C) Tenable Network Security, Inc.
#
# The descriptive text is (C) Scientific Linux.
#

include("compat.inc");

if (description)
{
  script_id(60561);
  script_version("$Revision: 1.3 $");
  script_cvs_date("$Date: 2016/12/14 20:22:14 $");

  script_cve_id("CVE-2008-3658", "CVE-2008-3660", "CVE-2008-5498", "CVE-2008-5557", "CVE-2008-5814", "CVE-2009-0754");

  script_name(english:"Scientific Linux Security Update : php on SL3.x, SL4.x, SL5.x i386/x86_64");
  script_summary(english:"Checks rpm output for the updated packages");

  script_set_attribute(
    attribute:"synopsis", 
    value:
"The remote Scientific Linux host is missing one or more security
updates."
  );
  script_set_attribute(
    attribute:"description", 
    value:
"A heap-based buffer overflow flaw was found in PHP's mbstring
extension. A remote attacker able to pass arbitrary input to a PHP
script using mbstring conversion functions could cause the PHP
interpreter to crash or, possibly, execute arbitrary code.
(CVE-2008-5557)

A flaw was found in the handling of the 'mbstring.func_overload'
configuration setting. A value set for one virtual host, or in a
user's .htaccess file, was incorrectly applied to other virtual hosts
on the same server, causing the handling of multibyte character
strings to not work correctly. (CVE-2009-0754)

A buffer overflow flaw was found in PHP's imageloadfont function. If a
PHP script allowed a remote attacker to load a carefully crafted font
file, it could cause the PHP interpreter to crash or, possibly,
execute arbitrary code. (CVE-2008-3658)

A flaw was found in the way PHP handled certain file extensions when
running in FastCGI mode. If the PHP interpreter was being executed via
FastCGI, a remote attacker could create a request which would cause
the PHP interpreter to crash. (CVE-2008-3660)

A cross-site scripting flaw was found in a way PHP reported errors for
invalid cookies. If the PHP interpreter had 'display_errors' enabled,
a remote attacker able to set a specially crafted cookie on a victim's
system could possibly inject arbitrary HTML into an error message
generated by PHP. (CVE-2008-5814) - SL5 Only

A memory disclosure flaw was found in the PHP gd extension's
imagerotate function. A remote attacker able to pass arbitrary values
as the 'background color' argument of the function could, possibly,
view portions of the PHP interpreter's memory. (CVE-2008-5498)

The httpd web server must be restarted for the changes to take effect."
  );
  # http://listserv.fnal.gov/scripts/wa.exe?A2=ind0904&L=scientific-linux-errata&T=0&P=334
  script_set_attribute(
    attribute:"see_also",
    value:"http://www.nessus.org/u?534933bb"
  );
  script_set_attribute(attribute:"solution", value:"Update the affected packages.");
  script_set_cvss_base_vector("CVSS2#AV:N/AC:L/Au:N/C:C/I:C/A:C");
  script_cwe_id(20, 79, 119, 134, 200);

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"x-cpe:/o:fermilab:scientific_linux");

  script_set_attribute(attribute:"patch_publication_date", value:"2009/04/06");
  script_set_attribute(attribute:"plugin_publication_date", value:"2012/08/01");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_copyright(english:"This script is Copyright (C) 2012-2016 Tenable Network Security, Inc.");
  script_family(english:"Scientific Linux Local Security Checks");

  script_dependencies("ssh_get_info.nasl");
  script_require_keys("Host/local_checks_enabled", "Host/cpu", "Host/RedHat/release", "Host/RedHat/rpm-list");

  exit(0);
}


include("audit.inc");
include("global_settings.inc");
include("rpm.inc");


if (!get_kb_item("Host/local_checks_enabled")) audit(AUDIT_LOCAL_CHECKS_NOT_ENABLED);
release = get_kb_item("Host/RedHat/release");
if (isnull(release) || "Scientific Linux " >!< release) audit(AUDIT_HOST_NOT, "running Scientific Linux");
if (!get_kb_item("Host/RedHat/rpm-list")) audit(AUDIT_PACKAGE_LIST_MISSING);

cpu = get_kb_item("Host/cpu");
if (isnull(cpu)) audit(AUDIT_UNKNOWN_ARCH);
if (cpu >!< "x86_64" && cpu !~ "^i[3-6]86$") audit(AUDIT_LOCAL_CHECKS_NOT_IMPLEMENTED, "Scientific Linux", cpu);


flag = 0;
if (rpm_check(release:"SL3", reference:"php-4.3.2-51.ent")) flag++;
if (rpm_check(release:"SL3", reference:"php-devel-4.3.2-51.ent")) flag++;
if (rpm_check(release:"SL3", reference:"php-imap-4.3.2-51.ent")) flag++;
if (rpm_check(release:"SL3", reference:"php-ldap-4.3.2-51.ent")) flag++;
if (rpm_check(release:"SL3", reference:"php-mysql-4.3.2-51.ent")) flag++;
if (rpm_check(release:"SL3", reference:"php-odbc-4.3.2-51.ent")) flag++;
if (rpm_check(release:"SL3", reference:"php-pgsql-4.3.2-51.ent")) flag++;

if (rpm_check(release:"SL4", reference:"php-4.3.9-3.22.15")) flag++;
if (rpm_check(release:"SL4", reference:"php-devel-4.3.9-3.22.15")) flag++;
if (rpm_check(release:"SL4", reference:"php-domxml-4.3.9-3.22.15")) flag++;
if (rpm_check(release:"SL4", reference:"php-gd-4.3.9-3.22.15")) flag++;
if (rpm_check(release:"SL4", reference:"php-imap-4.3.9-3.22.15")) flag++;
if (rpm_check(release:"SL4", reference:"php-ldap-4.3.9-3.22.15")) flag++;
if (rpm_check(release:"SL4", reference:"php-mbstring-4.3.9-3.22.15")) flag++;
if (rpm_check(release:"SL4", reference:"php-mysql-4.3.9-3.22.15")) flag++;
if (rpm_check(release:"SL4", reference:"php-ncurses-4.3.9-3.22.15")) flag++;
if (rpm_check(release:"SL4", reference:"php-odbc-4.3.9-3.22.15")) flag++;
if (rpm_check(release:"SL4", reference:"php-pear-4.3.9-3.22.15")) flag++;
if (rpm_check(release:"SL4", reference:"php-pgsql-4.3.9-3.22.15")) flag++;
if (rpm_check(release:"SL4", reference:"php-snmp-4.3.9-3.22.15")) flag++;
if (rpm_check(release:"SL4", reference:"php-xmlrpc-4.3.9-3.22.15")) flag++;

if (rpm_check(release:"SL5", reference:"php-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-bcmath-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-cli-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-common-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-dba-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-devel-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-gd-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-imap-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-ldap-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-mbstring-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-mysql-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-ncurses-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-odbc-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-pdo-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-pgsql-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-snmp-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-soap-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-xml-5.1.6-23.2.el5_3")) flag++;
if (rpm_check(release:"SL5", reference:"php-xmlrpc-5.1.6-23.2.el5_3")) flag++;


if (flag)
{
  if (report_verbosity > 0) security_hole(port:0, extra:rpm_report_get());
  else security_hole(0);
  exit(0);
}
else audit(AUDIT_HOST_NOT, "affected");
