#
# (C) Tenable Network Security, Inc.
#
# The descriptive text is (C) Scientific Linux.
#

include("compat.inc");

if (description)
{
  script_id(60327);
  script_version("$Revision: 1.1 $");
  script_cvs_date("$Date: 2012/08/01 14:38:53 $");

  script_cve_id("CVE-2006-7228", "CVE-2007-2052", "CVE-2007-4965");

  script_name(english:"Scientific Linux Security Update : python on SL4.x, SL3.x i386/x86_64");
  script_summary(english:"Checks rpm output for the updated packages");

  script_set_attribute(
    attribute:"synopsis", 
    value:
"The remote Scientific Linux host is missing one or more security
updates."
  );
  script_set_attribute(
    attribute:"description", 
    value:
"An integer overflow flaw was discovered in the way Python's pcre
module handled certain regular expressions. If a Python application
used the pcre module to compile and execute untrusted regular
expressions, it may be possible to cause the application to crash, or
allow arbitrary code execution with the privileges of the Python
interpreter. (CVE-2006-7228)

A flaw was discovered in the strxfrm() function of Python's locale
module. Strings generated by this function were not properly
NULL-terminated. This may possibly cause disclosure of data stored in
the memory of a Python application using this function.
(CVE-2007-2052)

Multiple integer overflow flaws were discovered in Python's imageop
module. If an application written in Python used the imageop module to
process untrusted images, it could cause the application to crash,
enter an infinite loop, or possibly execute arbitrary code with the
privileges of the Python interpreter. (CVE-2007-4965)"
  );
  # http://listserv.fnal.gov/scripts/wa.exe?A2=ind0712&L=scientific-linux-errata&T=0&P=1527
  script_set_attribute(
    attribute:"see_also",
    value:"http://www.nessus.org/u?ccfc71a1"
  );
  script_set_attribute(attribute:"solution", value:"Update the affected packages.");
  script_set_cvss_base_vector("CVSS2#AV:N/AC:M/Au:N/C:P/I:P/A:P");
  script_cwe_id(189);

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"x-cpe:/o:fermilab:scientific_linux");

  script_set_attribute(attribute:"patch_publication_date", value:"2007/12/10");
  script_set_attribute(attribute:"plugin_publication_date", value:"2012/08/01");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_copyright(english:"This script is Copyright (C) 2012 Tenable Network Security, Inc.");
  script_family(english:"Scientific Linux Local Security Checks");

  script_dependencies("ssh_get_info.nasl");
  script_require_keys("Host/local_checks_enabled", "Host/cpu", "Host/RedHat/release", "Host/RedHat/rpm-list");

  exit(0);
}


include("audit.inc");
include("global_settings.inc");
include("rpm.inc");


if (!get_kb_item("Host/local_checks_enabled")) audit(AUDIT_LOCAL_CHECKS_NOT_ENABLED);
release = get_kb_item("Host/RedHat/release");
if (isnull(release) || "Scientific Linux " >!< release) audit(AUDIT_HOST_NOT, "running Scientific Linux");
if (!get_kb_item("Host/RedHat/rpm-list")) audit(AUDIT_PACKAGE_LIST_MISSING);

cpu = get_kb_item("Host/cpu");
if (isnull(cpu)) audit(AUDIT_UNKNOWN_ARCH);
if (cpu >!< "x86_64" && cpu !~ "^i[3-6]86$") audit(AUDIT_LOCAL_CHECKS_NOT_IMPLEMENTED, "Scientific Linux", cpu);


flag = 0;
if (rpm_check(release:"SL3", reference:"python-2.2.3-6.8")) flag++;
if (rpm_check(release:"SL3", reference:"python-devel-2.2.3-6.8")) flag++;
if (rpm_check(release:"SL3", reference:"python-docs-2.2.3-6.8")) flag++;
if (rpm_check(release:"SL3", reference:"python-tools-2.2.3-6.8")) flag++;
if (rpm_check(release:"SL3", reference:"tkinter-2.2.3-6.8")) flag++;

if (rpm_check(release:"SL4", cpu:"i386", reference:"python-2.3.4-14.4.el4_6.1")) flag++;
if (rpm_check(release:"SL4", cpu:"x86_64", reference:"python-2.3.4-14.4.el4.1")) flag++;
if (rpm_check(release:"SL4", cpu:"i386", reference:"python-devel-2.3.4-14.4.el4_6.1")) flag++;
if (rpm_check(release:"SL4", cpu:"x86_64", reference:"python-devel-2.3.4-14.4.el4.1")) flag++;
if (rpm_check(release:"SL4", cpu:"i386", reference:"python-docs-2.3.4-14.4.el4_6.1")) flag++;
if (rpm_check(release:"SL4", cpu:"x86_64", reference:"python-docs-2.3.4-14.4.el4.1")) flag++;
if (rpm_check(release:"SL4", cpu:"i386", reference:"python-tools-2.3.4-14.4.el4_6.1")) flag++;
if (rpm_check(release:"SL4", cpu:"x86_64", reference:"python-tools-2.3.4-14.4.el4.1")) flag++;
if (rpm_check(release:"SL4", cpu:"i386", reference:"tkinter-2.3.4-14.4.el4_6.1")) flag++;
if (rpm_check(release:"SL4", cpu:"x86_64", reference:"tkinter-2.3.4-14.4.el4.1")) flag++;


if (flag)
{
  if (report_verbosity > 0) security_warning(port:0, extra:rpm_report_get());
  else security_warning(0);
  exit(0);
}
else audit(AUDIT_HOST_NOT, "affected");
