#
# (C) Tenable Network Security, Inc.
#
# The descriptive text and package checks in this plugin were
# extracted from SUSE update advisory SUSE-SU-2016:2397-1.
# The text itself is copyright (C) SUSE.
#

include("compat.inc");

if (description)
{
  script_id(93768);
  script_version("$Revision: 2.3 $");
  script_cvs_date("$Date: 2016/12/27 20:24:10 $");

  script_cve_id("CVE-2015-8079", "CVE-2016-6354");
  script_osvdb_id(119691, 142032);

  script_name(english:"SUSE SLED12 / SLES12 Security Update : flex, at, bogofilter, cyrus-imapd, kdelibs4, libQtWebKit4, libbonobo, mdbtools, netpbm, openslp, sgmltool, virtuoso, libqt5-qtwebkit (SUSE-SU-2016:2397-1)");
  script_summary(english:"Checks rpm output for the updated packages.");

  script_set_attribute(
    attribute:"synopsis", 
    value:"The remote SUSE host is missing one or more security updates."
  );
  script_set_attribute(
    attribute:"description", 
    value:
"Various packages included vulnerable parsers generated by 'flex'. This
update provides a fixed 'flex' package and also rebuilds of packages
that might have security issues caused by the auto generated code.
Flex itself was updated to fix a buffer overflow in the generated
scanner (bsc#990856, CVE-2016-6354) Packages that were rebuilt with
the fixed flex :

  - at

  - bogofilter

  - cyrus-imapd

  - kdelibs4

  - libQtWebKit4

  - libbonobo

  - mdbtools

  - netpbm

  - openslp

  - sgmltool

  - virtuoso Also libqt5-qtwebkit received an additional
    security fix :

  - CVE-2015-8079: QtWebKit logs visited URLs to
    WebpageIcons.db in private browsing mode (bsc#954210).

Note that Tenable Network Security has extracted the preceding
description block directly from the SUSE security advisory. Tenable
has attempted to automatically clean and format it as much as possible
without introducing additional issues."
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.suse.com/954210"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://bugzilla.suse.com/990856"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://www.suse.com/security/cve/CVE-2015-8079.html"
  );
  script_set_attribute(
    attribute:"see_also",
    value:"https://www.suse.com/security/cve/CVE-2016-6354.html"
  );
  # https://www.suse.com/support/update/announcement/2016/suse-su-20162397-1.html
  script_set_attribute(
    attribute:"see_also",
    value:"http://www.nessus.org/u?3bf65058"
  );
  script_set_attribute(
    attribute:"solution", 
    value:
"To install this SUSE Security Update use YaST online_update.
Alternatively you can run the command listed for your product :

SUSE Linux Enterprise Workstation Extension 12-SP1:zypper in -t patch
SUSE-SLE-WE-12-SP1-2016-1390=1

SUSE Linux Enterprise Software Development Kit 12-SP1:zypper in -t
patch SUSE-SLE-SDK-12-SP1-2016-1390=1

SUSE Linux Enterprise Server 12-SP1:zypper in -t patch
SUSE-SLE-SERVER-12-SP1-2016-1390=1

SUSE Linux Enterprise Desktop 12-SP1:zypper in -t patch
SUSE-SLE-DESKTOP-12-SP1-2016-1390=1

To bring your system up-to-date, use 'zypper patch'."
  );
  script_set_cvss_base_vector("CVSS2#AV:N/AC:L/Au:N/C:P/I:P/A:P");
  script_set_cvss_temporal_vector("CVSS2#E:U/RL:OF/RC:C");
  script_set_cvss3_base_vector("CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H");
  script_set_attribute(attribute:"exploitability_ease", value:"No known exploits are available");
  script_set_attribute(attribute:"exploit_available", value:"false");

  script_set_attribute(attribute:"plugin_type", value:"local");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:at");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:at-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:at-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:bogofilter");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:bogofilter-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:bogofilter-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:cyrus-imapd-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:cyrus-imapd-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:flex");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:flex-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:flex-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:kdelibs4-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:kdelibs4-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:libQtWebKit4");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:libQtWebKit4-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:libQtWebKit4-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:libbonobo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:libbonobo-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:libbonobo-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:libbonobo-doc");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:libbonobo-doc-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:libkde4");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:libkde4-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:libkdecore4");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:libkdecore4-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:libksuseinstall1");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:libksuseinstall1-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:libnetpbm11");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:libnetpbm11-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:netpbm");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:netpbm-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:netpbm-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:openslp");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:openslp-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:openslp-debugsource");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:openslp-server");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:openslp-server-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:perl-Cyrus-IMAP");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:perl-Cyrus-IMAP-debuginfo");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:perl-Cyrus-SIEVE-managesieve");
  script_set_attribute(attribute:"cpe", value:"p-cpe:/a:novell:suse_linux:perl-Cyrus-SIEVE-managesieve-debuginfo");
  script_set_attribute(attribute:"cpe", value:"cpe:/o:novell:suse_linux:12");

  script_set_attribute(attribute:"patch_publication_date", value:"2016/09/27");
  script_set_attribute(attribute:"plugin_publication_date", value:"2016/09/28");
  script_end_attributes();

  script_category(ACT_GATHER_INFO);
  script_copyright(english:"This script is Copyright (C) 2016 Tenable Network Security, Inc.");
  script_family(english:"SuSE Local Security Checks");

  script_dependencies("ssh_get_info.nasl");
  script_require_keys("Host/local_checks_enabled", "Host/cpu", "Host/SuSE/release", "Host/SuSE/rpm-list");

  exit(0);
}


include("audit.inc");
include("global_settings.inc");
include("rpm.inc");


if (!get_kb_item("Host/local_checks_enabled")) audit(AUDIT_LOCAL_CHECKS_NOT_ENABLED);
release = get_kb_item("Host/SuSE/release");
if (isnull(release) || release !~ "^(SLED|SLES)") audit(AUDIT_OS_NOT, "SUSE");
os_ver = eregmatch(pattern: "^(SLE(S|D)\d+)", string:release);
if (isnull(os_ver)) audit(AUDIT_UNKNOWN_APP_VER, "SUSE");
os_ver = os_ver[1];
if (! ereg(pattern:"^(SLED12|SLES12)$", string:os_ver)) audit(AUDIT_OS_NOT, "SUSE SLED12 / SLES12", "SUSE " + os_ver);

if (!get_kb_item("Host/SuSE/rpm-list")) audit(AUDIT_PACKAGE_LIST_MISSING);

cpu = get_kb_item("Host/cpu");
if (isnull(cpu)) audit(AUDIT_UNKNOWN_ARCH);
if (cpu !~ "^i[3-6]86$" && "x86_64" >!< cpu && "s390x" >!< cpu) audit(AUDIT_LOCAL_CHECKS_NOT_IMPLEMENTED, "SUSE " + os_ver, cpu);

sp = get_kb_item("Host/SuSE/patchlevel");
if (isnull(sp)) sp = "0";
if (os_ver == "SLES12" && (! ereg(pattern:"^(1)$", string:sp))) audit(AUDIT_OS_NOT, "SLES12 SP1", os_ver + " SP" + sp);
if (os_ver == "SLED12" && (! ereg(pattern:"^(1)$", string:sp))) audit(AUDIT_OS_NOT, "SLED12 SP1", os_ver + " SP" + sp);


flag = 0;
if (rpm_check(release:"SLES12", sp:"1", cpu:"x86_64", reference:"libQtWebKit4-4.8.6+2.3.3-3.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", cpu:"x86_64", reference:"libQtWebKit4-debuginfo-4.8.6+2.3.3-3.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", cpu:"x86_64", reference:"libQtWebKit4-debugsource-4.8.6+2.3.3-3.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", cpu:"x86_64", reference:"libQtWebKit4-32bit-4.8.6+2.3.3-3.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", cpu:"x86_64", reference:"libQtWebKit4-debuginfo-32bit-4.8.6+2.3.3-3.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"at-3.1.14-7.3")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"at-debuginfo-3.1.14-7.3")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"at-debugsource-3.1.14-7.3")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"cyrus-imapd-debuginfo-2.3.18-40.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"cyrus-imapd-debugsource-2.3.18-40.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"flex-2.5.37-8.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"flex-debuginfo-2.5.37-8.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"flex-debugsource-2.5.37-8.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"kdelibs4-debuginfo-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"kdelibs4-debugsource-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libbonobo-2.32.1-16.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libbonobo-debuginfo-2.32.1-16.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libbonobo-debugsource-2.32.1-16.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libbonobo-doc-2.32.1-16.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libbonobo-doc-debuginfo-2.32.1-16.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libkde4-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libkde4-debuginfo-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libkdecore4-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libkdecore4-debuginfo-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libksuseinstall1-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libksuseinstall1-debuginfo-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libnetpbm11-10.66.3-4.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libnetpbm11-debuginfo-10.66.3-4.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"netpbm-10.66.3-4.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"netpbm-debuginfo-10.66.3-4.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"netpbm-debugsource-10.66.3-4.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"openslp-2.0.0-11.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"openslp-debuginfo-2.0.0-11.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"openslp-debugsource-2.0.0-11.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"openslp-server-2.0.0-11.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"openslp-server-debuginfo-2.0.0-11.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"perl-Cyrus-IMAP-2.3.18-40.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"perl-Cyrus-IMAP-debuginfo-2.3.18-40.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"perl-Cyrus-SIEVE-managesieve-2.3.18-40.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"perl-Cyrus-SIEVE-managesieve-debuginfo-2.3.18-40.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"flex-32bit-2.5.37-8.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"flex-debuginfo-32bit-2.5.37-8.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libbonobo-32bit-2.32.1-16.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libbonobo-debuginfo-32bit-2.32.1-16.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libkde4-32bit-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libkde4-debuginfo-32bit-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libkdecore4-32bit-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libkdecore4-debuginfo-32bit-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libksuseinstall1-32bit-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libksuseinstall1-debuginfo-32bit-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libnetpbm11-32bit-10.66.3-4.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"libnetpbm11-debuginfo-32bit-10.66.3-4.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"openslp-32bit-2.0.0-11.1")) flag++;
if (rpm_check(release:"SLES12", sp:"1", reference:"openslp-debuginfo-32bit-2.0.0-11.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"at-3.1.14-7.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"at-debuginfo-3.1.14-7.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"at-debugsource-3.1.14-7.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"bogofilter-1.2.4-5.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"bogofilter-debuginfo-1.2.4-5.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"bogofilter-debugsource-1.2.4-5.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"kdelibs4-debuginfo-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"kdelibs4-debugsource-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libQtWebKit4-32bit-4.8.6+2.3.3-3.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libQtWebKit4-4.8.6+2.3.3-3.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libQtWebKit4-debuginfo-32bit-4.8.6+2.3.3-3.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libQtWebKit4-debuginfo-4.8.6+2.3.3-3.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libQtWebKit4-debugsource-4.8.6+2.3.3-3.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libbonobo-2.32.1-16.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libbonobo-32bit-2.32.1-16.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libbonobo-debuginfo-2.32.1-16.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libbonobo-debuginfo-32bit-2.32.1-16.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libbonobo-debugsource-2.32.1-16.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libkde4-32bit-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libkde4-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libkde4-debuginfo-32bit-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libkde4-debuginfo-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libkdecore4-32bit-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libkdecore4-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libkdecore4-debuginfo-32bit-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libkdecore4-debuginfo-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libksuseinstall1-32bit-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libksuseinstall1-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libksuseinstall1-debuginfo-32bit-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libksuseinstall1-debuginfo-4.12.0-7.3")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libnetpbm11-10.66.3-4.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libnetpbm11-32bit-10.66.3-4.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libnetpbm11-debuginfo-10.66.3-4.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"libnetpbm11-debuginfo-32bit-10.66.3-4.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"netpbm-10.66.3-4.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"netpbm-debuginfo-10.66.3-4.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"netpbm-debugsource-10.66.3-4.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"openslp-2.0.0-11.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"openslp-32bit-2.0.0-11.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"openslp-debuginfo-2.0.0-11.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"openslp-debuginfo-32bit-2.0.0-11.1")) flag++;
if (rpm_check(release:"SLED12", sp:"1", cpu:"x86_64", reference:"openslp-debugsource-2.0.0-11.1")) flag++;


if (flag)
{
  if (report_verbosity > 0) security_hole(port:0, extra:rpm_report_get());
  else security_hole(0);
  exit(0);
}
else
{
  tested = pkg_tests_get();
  if (tested) audit(AUDIT_PACKAGE_NOT_AFFECTED, tested);
  else audit(AUDIT_PACKAGE_NOT_INSTALLED, "flex / at / bogofilter / cyrus-imapd / kdelibs4 / libQtWebKit4 / libbonobo / mdbtools / netpbm / openslp / sgmltool / virtuoso / libqt5-qtwebkit");
}
